BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "AdditionalCosts" (
	"AdditionalCostID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"LK_DetailId"	INTEGER NOT NULL,
	"LK_ItemId"	INTEGER NOT NULL,
	"Price"	REAL,
	"Total"	REAL,
	"AssignmentQuotation"	INTEGER,
	"AssignmentCalculation"	INTEGER,
	"Reference"	INTEGER,
	"Name"	TEXT,
	"SCurrency"	TEXT,
	PRIMARY KEY("AdditionalCostID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID"),
	FOREIGN KEY("LK_DetailId") REFERENCES "CalcDetailNames"("CalcDetailNameID"),
	FOREIGN KEY("LK_ItemId") REFERENCES "CalcItemNames"("CalcItemNameID")
);
CREATE TABLE IF NOT EXISTS "Address" (
	"AddressID"	INTEGER NOT NULL,
	"Address1"	TEXT,
	"Address2"	TEXT,
	"Address3"	TEXT,
	"Address4"	TEXT,
	"Address5"	TEXT,
	"Address6"	TEXT,
	"Address7"	TEXT,
	"Address8"	TEXT,
	"Address9"	TEXT,
	"Phone1"	TEXT,
	"Phone2"	TEXT,
	"Fax"	TEXT,
	"Email"	TEXT,
	"CustomerNo"	TEXT,
	"ExternalKey"	TEXT,
	"ZipCode"	TEXT,
	"IsDummy"	INTEGER,
	PRIMARY KEY("AddressID")
);
CREATE TABLE IF NOT EXISTS "AllArticles" (
	"AllArticleID"	INTEGER NOT NULL,
	"SupplierId"	INTEGER NOT NULL,
	"LK_ManufacturerId"	INTEGER,
	"LK_ColorId"	INTEGER,
	"LK_DiscountId"	INTEGER,
	"LK_KfmKeyId"	INTEGER,
	"xSashGUID"	TEXT,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"PUAmount"	REAL,
	"Units"	REAL,
	"Units_Output"	REAL,
	"Units_Unit"	TEXT,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Depth"	REAL,
	"Depth_Output"	REAL,
	"Depth_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"IsManual"	INTEGER DEFAULT 0,
	"IsInactive"	INTEGER DEFAULT 0,
	"Color"	TEXT,
	"ColorTypeInternal"	INTEGER,
	"ColorInfoInternal"	TEXT,
	"Price"	REAL,
	"PriceGross"	REAL,
	"Discount"	REAL,
	"IsSalesPriceItem"	INTEGER DEFAULT 0,
	"IsAdditional"	INTEGER DEFAULT 0,
	"PUSize"	REAL,
	"PUSize_Output"	REAL,
	"PUSize_Unit"	TEXT,
	"IsPair"	INTEGER DEFAULT 0,
	"SubSize"	REAL,
	"Material"	INTEGER,
	"MaterialDescription"	TEXT,
	"ArticleType"	INTEGER,
	"SubType"	INTEGER,
	"PieceListType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"ProcessingPoint"	TEXT,
	"ProcessingPointType"	INTEGER,
	"ProductGroup"	TEXT,
	"AreaOffer"	TEXT,
	"UsageOffer"	TEXT,
	"HashCode"	TEXT,
	"IsMixedPrice"	INTEGER DEFAULT 0,
	"MixedQty1"	REAL,
	"MixedQty2"	REAL,
	"IsLength"	INTEGER DEFAULT 0,
	"IsArea"	INTEGER DEFAULT 0,
	"IsVolume"	INTEGER DEFAULT 0,
	"IsWeight"	INTEGER DEFAULT 0,
	"IsPiece"	INTEGER DEFAULT 0,
	"SupplierCode"	INTEGER,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"HasSubArticles"	INTEGER DEFAULT 0,
	"Dimension1"	REAL,
	"Dimension1_Output"	REAL,
	"Dimension1_Unit"	TEXT,
	"Dimension2"	REAL,
	"Dimension2_Output"	REAL,
	"Dimension2_Unit"	TEXT,
	"Dimension3"	REAL,
	"Dimension3_Output"	REAL,
	"Dimension3_Unit"	TEXT,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	"DoNotEstimate"	INTEGER DEFAULT 0,
	"IsResidual"	INTEGER DEFAULT 0,
	"BottomExtension"	REAL,
	"BottomExtension_Output"	REAL,
	"BottomExtension_Unit"	TEXT,
	"TopExtension"	REAL,
	"TopExtension_Output"	REAL,
	"TopExtension_Unit"	TEXT,
	"ExtensionSideA"	REAL,
	"ExtensionSideA_Output"	REAL,
	"ExtensionSideA_Unit"	TEXT,
	"ExtensionSideB"	REAL,
	"ExtensionSideB_Output"	REAL,
	"ExtensionSideB_Unit"	TEXT,
	"SubNo"	INTEGER,
	"ArticleTypePrintout"	INTEGER,
	"CoatingColor"	INTEGER DEFAULT 0,
	"ShowInSashList"	INTEGER DEFAULT 0,
	"ArticleHashcode"	TEXT,
	"Alias"	TEXT,
	PRIMARY KEY("AllArticleID"),
	FOREIGN KEY("SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "AllProfiles" (
	"AllProfileID"	INTEGER NOT NULL,
	"SupplierId"	INTEGER NOT NULL,
	"LK_KfmKeyId"	INTEGER,
	"LK_ManufacturerId"	INTEGER,
	"LK_ColorId"	INTEGER,
	"LK_InnerColorId"	INTEGER,
	"LK_OuterColorId"	INTEGER,
	"LK_DiscountId"	INTEGER,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"PUAmount"	REAL,
	"Units"	REAL,
	"Units_Output"	REAL,
	"Units_Unit"	TEXT,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"UsedLength"	REAL,
	"UsedLength_Output"	REAL,
	"UsedLength_Unit"	TEXT,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"IsManual"	INTEGER DEFAULT 0,
	"IsInactive"	INTEGER DEFAULT 0,
	"IsArched"	INTEGER DEFAULT 0,
	"IsSpecialLength"	INTEGER DEFAULT 0,
	"IsResidualLength"	INTEGER DEFAULT 0,
	"IsFixedLength"	INTEGER DEFAULT 0,
	"FixSurcharge"	REAL,
	"ResidualIgnored"	INTEGER DEFAULT 0,
	"Color"	TEXT,
	"InnerColor"	TEXT,
	"OuterColor"	TEXT,
	"IsDualColor"	INTEGER DEFAULT 0,
	"PieceListType"	INTEGER,
	"ColorTypeInternal"	INTEGER,
	"ColorInfoInternal"	TEXT,
	"InnerColorTypeInternal"	INTEGER,
	"InnerColorInfoInternal"	TEXT,
	"OuterColorTypeInternal"	INTEGER,
	"OuterColorInfoInternal"	TEXT,
	"ColorCombinationGUID"	TEXT,
	"Price"	REAL,
	"PriceGross"	REAL,
	"PriceCoating"	REAL,
	"Discount"	REAL,
	"IsSalesPriceItem"	INTEGER DEFAULT 0,
	"IsAdditional"	INTEGER DEFAULT 0,
	"PUSize"	REAL,
	"PUSize_Output"	REAL,
	"PUSize_Unit"	TEXT,
	"SubSize"	REAL,
	"Material"	INTEGER,
	"MaterialDescription"	TEXT,
	"ArticleType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"ProcessingPoint"	TEXT,
	"ProcessingPointType"	INTEGER,
	"ProductGroup"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"PerimeterBoundaryBox"	REAL,
	"PerimeterBoundaryBox_Output"	REAL,
	"PerimeterBoundaryBox_Unit"	TEXT,
	"VisibleSurface"	REAL,
	"VisibleSurface_Output"	REAL,
	"VisibleSurface_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"ProfileHeight"	REAL,
	"ProfileHeight_Output"	REAL,
	"ProfileHeight_Unit"	TEXT,
	"ProfileWidth"	REAL,
	"ProfileWidth_Output"	REAL,
	"ProfileWidth_Unit"	TEXT,
	"ProfileOrderHeight"	REAL,
	"ProfileOrderHeight_Output"	REAL,
	"ProfileOrderHeight_Unit"	TEXT,
	"ProfileOrderWidth"	REAL,
	"ProfileOrderWidth_Output"	REAL,
	"ProfileOrderWidth_Unit"	TEXT,
	"IsMixedPrice"	INTEGER DEFAULT 0,
	"MixedQty1"	REAL,
	"MixedQty2"	REAL,
	"SupplierCode"	INTEGER,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	"DoNotEstimate"	INTEGER DEFAULT 0,
	"BottomExtension"	REAL,
	"BottomExtension_Output"	REAL,
	"BottomExtension_Unit"	TEXT,
	"TopExtension"	REAL,
	"TopExtension_Output"	REAL,
	"TopExtension_Unit"	TEXT,
	"ExtensionSideA"	REAL,
	"ExtensionSideA_Output"	REAL,
	"ExtensionSideA_Unit"	TEXT,
	"ExtensionSideB"	REAL,
	"ExtensionSideB_Output"	REAL,
	"ExtensionSideB_Unit"	TEXT,
	"CoatingColor"	INTEGER DEFAULT 0,
	"WoodType"	INTEGER,
	"WoodTypeDescription"	TEXT,
	"ArticleTypePrintout"	INTEGER,
	"ResidualLength"	REAL,
	"ResidualLength_Output"	REAL,
	"ResidualLength_Unit"	TEXT,
	"MinUsableLen"	REAL,
	"MinUsableLen_Output"	REAL,
	"MinUsableLen_Unit"	TEXT,
	"WeightEstimation"	REAL,
	"WeightEstimation_Output"	REAL,
	"WeightEstimation_Unit"	TEXT,
	PRIMARY KEY("AllProfileID"),
	FOREIGN KEY("SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "Articles" (
	"ArticleID"	INTEGER NOT NULL,
	"InsertionId"	INTEGER NOT NULL,
	"LK_SupplierId"	INTEGER NOT NULL,
	"LK_KfmKeyId"	INTEGER,
	"LK_CalcItemNameId"	INTEGER,
	"LK_ManufacturerId"	INTEGER,
	"LK_ColorId"	INTEGER,
	"LK_DiscountId"	INTEGER,
	"xSegmentGUID"	TEXT,
	"xSashGUID"	TEXT,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"Layer"	INTEGER,
	"Units"	REAL,
	"Units_Output"	REAL,
	"Units_Unit"	TEXT,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Depth"	REAL,
	"Depth_Output"	REAL,
	"Depth_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"IsManual"	INTEGER DEFAULT 0,
	"IsInactive"	INTEGER DEFAULT 0,
	"IsAdditional"	INTEGER DEFAULT 0,
	"Color"	TEXT,
	"ColorTypeInternal"	INTEGER,
	"ColorInfoInternal"	TEXT,
	"Price"	REAL,
	"PriceGross"	REAL,
	"Discount"	REAL,
	"IsSalesPriceItem"	INTEGER DEFAULT 0,
	"PUSize"	REAL,
	"PUSize_Output"	REAL,
	"PUSize_Unit"	TEXT,
	"LockingBarInfo"	TEXT,
	"LockingBarPos"	TEXT,
	"LockingBarPosLong"	TEXT,
	"LockingBarPosEnum"	INTEGER,
	"IsMixedPrice"	INTEGER DEFAULT 0,
	"MixedQty1"	REAL,
	"MixedQty2"	REAL,
	"IsPair"	INTEGER DEFAULT 0,
	"SubSize"	REAL,
	"Material"	INTEGER,
	"MaterialDescription"	TEXT,
	"ArticleType"	INTEGER,
	"PieceListType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"MountingOrder"	INTEGER,
	"FromHardware"	INTEGER,
	"Hashcode"	TEXT,
	"AreaOffer"	TEXT,
	"UsageOffer"	TEXT,
	"InsertionNo"	INTEGER,
	"InsertionSubNo"	INTEGER,
	"IsLength"	INTEGER DEFAULT 0,
	"IsArea"	INTEGER DEFAULT 0,
	"IsVolume"	INTEGER DEFAULT 0,
	"IsWeight"	INTEGER DEFAULT 0,
	"IsPiece"	INTEGER DEFAULT 0,
	"ProcessingPoint"	TEXT,
	"ProcessingPointType"	INTEGER,
	"ProductGroup"	TEXT,
	"SupplierCode"	INTEGER,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"HasSubArticles"	INTEGER DEFAULT 0,
	"Dimension1"	REAL,
	"Dimension1_Output"	REAL,
	"Dimension1_Unit"	TEXT,
	"Dimension2"	REAL,
	"Dimension2_Output"	REAL,
	"Dimension2_Unit"	TEXT,
	"Dimension3"	REAL,
	"Dimension3_Output"	REAL,
	"Dimension3_Unit"	TEXT,
	"SubType"	INTEGER,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	"DoNotEstimate"	INTEGER DEFAULT 0,
	"BottomExtension"	REAL,
	"BottomExtension_Output"	REAL,
	"BottomExtension_Unit"	TEXT,
	"TopExtension"	REAL,
	"TopExtension_Output"	REAL,
	"TopExtension_Unit"	TEXT,
	"ExtensionSideA"	REAL,
	"ExtensionSideA_Output"	REAL,
	"ExtensionSideA_Unit"	TEXT,
	"ExtensionSideB"	REAL,
	"ExtensionSideB_Output"	REAL,
	"ExtensionSideB_Unit"	TEXT,
	"SubNo"	INTEGER,
	"ArticleTypePrintout"	INTEGER,
	"PriceManually"	REAL,
	"ShowInSashList"	INTEGER DEFAULT 0,
	"ArticleHashcode"	TEXT,
	"Alias"	TEXT,
	PRIMARY KEY("ArticleID"),
	FOREIGN KEY("InsertionId") REFERENCES "Insertions"("InsertionID"),
	FOREIGN KEY("LK_SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "CNCProfilePositions" (
	"CncProfilePositionId"	INTEGER NOT NULL,
	"ProfileGUID"	TEXT,
	"IsMacro"	INTEGER DEFAULT 0,
	"MacroTypeNr"	INTEGER,
	"MacroType"	TEXT,
	"MacroName"	TEXT,
	"MacroSubName"	TEXT,
	"SawId"	INTEGER NOT NULL,
	"BeschMakKey"	TEXT,
	"IsLaidOnProfile"	INTEGER DEFAULT 0,
	PRIMARY KEY("CncProfilePositionId"),
	FOREIGN KEY("SawId") REFERENCES "Saws"("SawID")
);
CREATE TABLE IF NOT EXISTS "CNCWorkPlanInfo" (
	"CNCWorkPlanInfoID"	INTEGER NOT NULL,
	"ProfileId"	INTEGER NOT NULL,
	"LK_SawId"	INTEGER NOT NULL,
	"ProfileNumber"	TEXT,
	"ProfileNumberOnCNC"	TEXT,
	"Barcode"	TEXT,
	"PositionNumber"	TEXT,
	"UsageInfo"	INTEGER,
	"InfoString1"	TEXT,
	"InfoString2"	TEXT,
	"InfoString3"	TEXT,
	"InfoString4"	TEXT,
	"AdditionalInfo1"	TEXT,
	"AdditionalInfo2"	TEXT,
	"AdditionalInfo3"	TEXT,
	"AdditionalInfo4"	TEXT,
	"SawInfoPosition"	INTEGER,
	"SawInfoBarcodeNumber"	INTEGER,
	"SawInfoBarLength"	REAL,
	"OrientationCount"	INTEGER,
	"IsCopy"	INTEGER DEFAULT 0,
	"DispBarcodeIndex"	INTEGER,
	"DispBarcode"	TEXT,
	"DispDrawing1_File"	TEXT,
	"DispDrawing1_WidthMM"	REAL,
	"DispDrawing1_HeightMM"	REAL,
	"DispDrawing1_Scale"	REAL,
	"DispDrawing1_Inside"	INTEGER,
	"DispDrawing1_CompCad"	BLOB,
	"DispDrawing2_File"	TEXT,
	"DispDrawing2_WidthMM"	REAL,
	"DispDrawing2_HeightMM"	REAL,
	"DispDrawing2_Scale"	REAL,
	"DispDrawing2_Inside"	INTEGER,
	"DispDrawing2_CompCad"	BLOB,
	"DispDrawing3_File"	TEXT,
	"DispDrawing3_WidthMM"	REAL,
	"DispDrawing3_HeightMM"	REAL,
	"DispDrawing3_Scale"	REAL,
	"DispDrawing3_Inside"	INTEGER,
	"DispDrawing3_CompCad"	BLOB,
	"DispDrawing4_File"	TEXT,
	"DispDrawing4_WidthMM"	REAL,
	"DispDrawing4_HeightMM"	REAL,
	"DispDrawing4_Scale"	REAL,
	"DispDrawing4_Inside"	INTEGER,
	"DispDrawing4_CompCad"	BLOB,
	"ProfileOrientation1_File"	TEXT,
	"ProfileOrientation1_WidthMM"	REAL,
	"ProfileOrientation1_HeightMM"	REAL,
	"ProfileOrientation1_Scale"	REAL,
	"ProfileOrientation1_Inside"	INTEGER,
	"ProfileOrientation1_CompCad"	BLOB,
	"ProfileOrientation2_File"	TEXT,
	"ProfileOrientation2_WidthMM"	REAL,
	"ProfileOrientation2_HeightMM"	REAL,
	"ProfileOrientation2_Scale"	REAL,
	"ProfileOrientation2_Inside"	INTEGER,
	"ProfileOrientation2_CompCad"	BLOB,
	"ProfileOrientation3_File"	TEXT,
	"ProfileOrientation3_WidthMM"	REAL,
	"ProfileOrientation3_HeightMM"	REAL,
	"ProfileOrientation3_Scale"	REAL,
	"ProfileOrientation3_Inside"	INTEGER,
	"ProfileOrientation3_CompCad"	BLOB,
	"ProfileOrientation4_File"	TEXT,
	"ProfileOrientation4_WidthMM"	REAL,
	"ProfileOrientation4_HeightMM"	REAL,
	"ProfileOrientation4_Scale"	REAL,
	"ProfileOrientation4_Inside"	INTEGER,
	"ProfileOrientation4_CompCad"	BLOB,
	PRIMARY KEY("CNCWorkPlanInfoID"),
	FOREIGN KEY("LK_SawId") REFERENCES "Saws"("SawID"),
	FOREIGN KEY("ProfileId") REFERENCES "Profiles"("ProfileID")
);
CREATE TABLE IF NOT EXISTS "CalcDetailItems" (
	"CalcDetailItemID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"LK_DetailId"	INTEGER NOT NULL,
	"LK_ItemId"	INTEGER NOT NULL,
	"Gross"	REAL,
	"GrossInclMult"	REAL,
	"Net"	REAL,
	"Overheads"	REAL,
	"SalesAndManagement"	REAL,
	"Interest"	REAL,
	"Transport"	REAL,
	"Profit"	REAL,
	"TotalPriceProfit"	REAL,
	"ProfitByDiscountGroup"	REAL,
	"AddOn"	REAL,
	"Commission"	REAL,
	"PlanningOffice"	REAL,
	"SurchargeCashDiscount"	REAL,
	"Total"	REAL,
	PRIMARY KEY("CalcDetailItemID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID"),
	FOREIGN KEY("LK_DetailId") REFERENCES "CalcDetailNames"("CalcDetailNameID"),
	FOREIGN KEY("LK_ItemId") REFERENCES "CalcItemNames"("CalcItemNameID")
);
CREATE TABLE IF NOT EXISTS "CalcDetailNames" (
	"CalcDetailNameID"	INTEGER NOT NULL,
	"DetailName"	TEXT,
	PRIMARY KEY("CalcDetailNameID")
);
CREATE TABLE IF NOT EXISTS "CalcItemNames" (
	"CalcItemNameID"	INTEGER NOT NULL,
	"ItemName"	TEXT,
	"SalesPriceItem"	INTEGER DEFAULT 0,
	"EstimationSector"	INTEGER,
	PRIMARY KEY("CalcItemNameID")
);
CREATE TABLE IF NOT EXISTS "Colors" (
	"ColorID"	INTEGER NOT NULL,
	"ColorName"	TEXT,
	"ColorDescription"	TEXT,
	"Thickness"	TEXT,
	"GlossLevel"	TEXT,
	"PowderID"	TEXT,
	"ColorType"	INTEGER,
	"ColorReference"	INTEGER,
	"AddressID"	INTEGER,
	"AddressName"	TEXT,
	"LaminationDecorInside"	TEXT,
	"LaminationDecorOutside"	TEXT,
	"LaminationBaseBody"	TEXT,
	"LaminationGasket"	TEXT,
	"AluHeaderShell"	TEXT,
	"IsLamination"	INTEGER DEFAULT 0,
	"ColorCombinationGUID"	TEXT,
	"ColorTypeSupplier"	INTEGER,
	PRIMARY KEY("ColorID")
);
CREATE TABLE IF NOT EXISTS "DeliveryStatusText" (
	"DeliveryStatusTextID"	INTEGER NOT NULL,
	"DeliveryStatus"	INTEGER,
	"StatusText"	TEXT,
	PRIMARY KEY("DeliveryStatusTextID")
);
CREATE TABLE IF NOT EXISTS "Dimensions" (
	"DimensionID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Orientation"	INTEGER,
	"FullDim"	INTEGER DEFAULT 0,
	"Auto"	INTEGER DEFAULT 0,
	"InsideView"	INTEGER DEFAULT 0,
	"PartialNo"	INTEGER,
	"DimValue"	REAL,
	"DimValue_Output"	REAL,
	"DimValue_Unit"	TEXT,
	"X0"	REAL,
	"Y0"	REAL,
	"X1"	REAL,
	"Y1"	REAL,
	"TextX0"	REAL,
	"TextY0"	REAL,
	"TextX1"	REAL,
	"TextY1"	REAL,
	PRIMARY KEY("DimensionID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationCE" (
	"ElevationCEId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"IdentKey"	INTEGER,
	"Numeration"	TEXT,
	"Description"	TEXT,
	"Performance"	TEXT,
	"Institution"	TEXT,
	"InstitutionShort"	TEXT,
	"Testreport"	TEXT,
	"ValidUntil"	TEXT,
	"DoPNumber"	TEXT,
	"AVCP"	TEXT,
	"EN"	TEXT,
	"ENDescription"	TEXT,
	PRIMARY KEY("ElevationCEId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationFrames" (
	"ElevationFramesId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"PictureI_File"	TEXT,
	"PictureI_WidthMM"	REAL,
	"PictureI_HeightMM"	REAL,
	"PictureI_Scale"	REAL,
	"PictureI_Inside"	INTEGER,
	"PictureI_CompCad"	BLOB,
	"PictureO_File"	TEXT,
	"PictureO_WidthMM"	REAL,
	"PictureO_HeightMM"	REAL,
	"PictureO_Scale"	REAL,
	"PictureO_Inside"	INTEGER,
	"PictureO_CompCad"	BLOB,
	"FramePictureI_File"	TEXT,
	"FramePictureI_WidthMM"	REAL,
	"FramePictureI_HeightMM"	REAL,
	"FramePictureI_Scale"	REAL,
	"FramePictureI_Inside"	INTEGER,
	"FramePictureI_CompCad"	BLOB,
	"FramePictureO_File"	TEXT,
	"FramePictureO_WidthMM"	REAL,
	"FramePictureO_HeightMM"	REAL,
	"FramePictureO_Scale"	REAL,
	"FramePictureO_Inside"	INTEGER,
	"FramePictureO_CompCad"	BLOB,
	"ElevationGUID"	TEXT,
	"BaseElementNumber"	INTEGER,
	"IsCoupling"	INTEGER DEFAULT 0,
	PRIMARY KEY("ElevationFramesId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationGroups" (
	"ElevationGroupID"	INTEGER NOT NULL,
	"HasMultiplePos"	INTEGER DEFAULT 0,
	"PhaseId"	INTEGER NOT NULL,
	PRIMARY KEY("ElevationGroupID"),
	FOREIGN KEY("PhaseId") REFERENCES "Phases"("PhaseID")
);
CREATE TABLE IF NOT EXISTS "ElevationPriceclass" (
	"ElevationPriceclassID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"PriceClass"	TEXT,
	"Information"	TEXT,
	"IsNet"	INTEGER DEFAULT 0,
	"ValueProfil"	REAL,
	"ValueAccessories"	REAL,
	"ValueHardware"	REAL,
	"WeightProfil"	REAL,
	"WeightProfil_Output"	REAL,
	"WeightProfil_Unit"	TEXT,
	PRIMARY KEY("ElevationPriceclassID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationStructCalc" (
	"ElevationStructCalcID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"InstallLocation"	INTEGER,
	"HeadDistanceFromGroundLevel"	REAL,
	"WindowRating"	TEXT,
	"CornerElevation"	INTEGER DEFAULT 0,
	"Load_U"	REAL,
	"Load_U_Output"	REAL,
	"Load_U_Unit"	TEXT,
	"Load_U_negative"	REAL,
	"Load_U_negative_Output"	REAL,
	"Load_U_negative_Unit"	TEXT,
	"Load_S"	REAL,
	"Load_S_Output"	REAL,
	"Load_S_Unit"	TEXT,
	"Load_S_negative"	REAL,
	"Load_S_negative_Output"	REAL,
	"Load_S_negative_Unit"	TEXT,
	"Load_W"	REAL,
	"Load_W_Output"	REAL,
	"Load_W_Unit"	TEXT,
	PRIMARY KEY("ElevationStructCalcID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationSurface" (
	"ElevationSurfaceID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"SurfaceType"	INTEGER,
	"SurfaceColor"	TEXT,
	"SurfacePrice"	REAL,
	"PriceIncColor"	INTEGER DEFAULT 0,
	"SurfaceTotal"	REAL,
	"SurfaceTotal_Unit"	TEXT,
	PRIMARY KEY("ElevationSurfaceID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationSystemAttributes" (
	"ElevationSystemAttributesId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"SystemAttribute"	TEXT,
	"SelectedAttributes"	TEXT,
	"SystemID"	INTEGER,
	PRIMARY KEY("ElevationSystemAttributesId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "ElevationWarnings" (
	"ElevationWarningID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Information"	TEXT,
	"Type"	INTEGER,
	"ShowHintInEstimation"	INTEGER DEFAULT 0,
	"ShowHintInAssemblyList"	INTEGER DEFAULT 0,
	"ShowHintInGlassOrder"	INTEGER DEFAULT 0,
	PRIMARY KEY("ElevationWarningID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "Elevations" (
	"ElevationID"	INTEGER NOT NULL,
	"ElevationGroupId"	INTEGER NOT NULL,
	"LK_BaseInnerColorId"	INTEGER,
	"LK_BaseOuterColorId"	INTEGER,
	"LK_InsertionInnerColorId"	INTEGER,
	"LK_InsertionOuterColorId"	INTEGER,
	"Name"	TEXT,
	"xGUID"	TEXT,
	"LinkedGUID"	TEXT,
	"LinkComment"	TEXT,
	"Amount"	REAL,
	"OrgAmount"	REAL,
	"InsertionGuidlinesLikeProject"	INTEGER DEFAULT 0,
	"OnlyEstimation"	INTEGER DEFAULT 0,
	"Alternative"	INTEGER DEFAULT 0,
	"Description"	TEXT,
	"TextPosText"	TEXT,
	"AutoDescription"	TEXT,
	"AutoDescriptionShort"	TEXT,
	"Model"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"Area"	REAL,
	"Area_Output"	REAL,
	"Area_Unit"	TEXT,
	"SystemCode"	TEXT,
	"SystemCode_Supplier"	TEXT,
	"SystemCode_Number"	TEXT,
	"SystemCode_BaseNumber"	TEXT,
	"SystemCode_OrderCode"	TEXT,
	"SystemCode_OriginalNumber"	TEXT,
	"SystemName"	TEXT,
	"SystemLongName"	TEXT,
	"SystemNameInternal"	TEXT,
	"SystemType"	INTEGER,
	"SystemRulePackage"	TEXT,
	"SystemGLL"	TEXT,
	"SystemSub"	TEXT,
	"SystemSelection1"	TEXT,
	"SystemSelection2"	TEXT,
	"SubSystemAsMainSystem"	INTEGER DEFAULT 0,
	"ElevationType"	INTEGER,
	"WoodType"	INTEGER,
	"WoodTypeDescription"	TEXT,
	"WoodDepth"	REAL,
	"WoodDepth_Output"	REAL,
	"WoodDepth_Unit"	TEXT,
	"Drainage"	INTEGER,
	"TConnections"	INTEGER,
	"TConnections_Description"	TEXT,
	"Corners"	INTEGER,
	"Corners_Description"	TEXT,
	"BaseCorners"	INTEGER,
	"BaseCorners_Description"	TEXT,
	"WindowCorners"	INTEGER,
	"WindowCorners_Description"	TEXT,
	"SashCorners"	INTEGER,
	"SashCorners_Description"	TEXT,
	"DoorCorners"	INTEGER,
	"DoorCorners_Description"	TEXT,
	"LengthDimsReferTo"	INTEGER,
	"SegmentLevel"	INTEGER,
	"IsSegment"	INTEGER DEFAULT 0,
	"Material"	TEXT,
	"CWConnectionInside"	TEXT,
	"CWConnectionOutside"	TEXT,
	"ImportOrigin"	INTEGER,
	"TextPosOrigin"	INTEGER,
	"SubNo"	INTEGER,
	"CEDataComplete"	INTEGER DEFAULT 0,
	"StaticCalculation"	INTEGER DEFAULT 0,
	"IsCurrentVersion"	INTEGER DEFAULT 0,
	"OffsetX"	REAL,
	"OffsetX_Output"	REAL,
	"OffsetX_Unit"	TEXT,
	"OffsetY"	REAL,
	"OffsetY_Output"	REAL,
	"OffsetY_Unit"	TEXT,
	"CreatedBy"	TEXT,
	"CreatedOn"	TEXT,
	"ChangedBy"	TEXT,
	"ChangedOn"	TEXT,
	"Picture1_File"	TEXT,
	"Picture1_WidthMM"	REAL,
	"Picture1_HeightMM"	REAL,
	"Picture1_Scale"	REAL,
	"Picture1_Inside"	INTEGER,
	"Picture1_CompCad"	BLOB,
	"Picture2_File"	TEXT,
	"Picture2_WidthMM"	REAL,
	"Picture2_HeightMM"	REAL,
	"Picture2_Scale"	REAL,
	"Picture2_Inside"	INTEGER,
	"Picture2_CompCad"	BLOB,
	"Picture3_File"	TEXT,
	"Picture3_WidthMM"	REAL,
	"Picture3_HeightMM"	REAL,
	"Picture3_Scale"	REAL,
	"Picture3_Inside"	INTEGER,
	"Picture3_CompCad"	BLOB,
	"Picture4_File"	TEXT,
	"Picture4_WidthMM"	REAL,
	"Picture4_HeightMM"	REAL,
	"Picture4_Scale"	REAL,
	"Picture4_Inside"	INTEGER,
	"Picture4_CompCad"	BLOB,
	"Picture5_File"	TEXT,
	"Picture5_WidthMM"	REAL,
	"Picture5_HeightMM"	REAL,
	"Picture5_Scale"	REAL,
	"Picture5_Inside"	INTEGER,
	"Picture5_CompCad"	BLOB,
	"SurveyPicture_File"	TEXT,
	"SurveyPicture_WidthMM"	REAL,
	"SurveyPicture_HeightMM"	REAL,
	"SurveyPicture_Scale"	REAL,
	"SurveyPicture_Inside"	INTEGER,
	"SurveyPicture_CompCad"	BLOB,
	"ProfileMem"	TEXT,
	"ProfileMemBlob"	,
	"ProfileMemBlobIsZipped"	INTEGER DEFAULT 0,
	"SealingToStructure"	INTEGER,
	"GlassGasket"	INTEGER,
	"CentreGasket"	INTEGER,
	"Manufacturing"	REAL,
	"Manufacturing2"	REAL,
	"Manufacturing3"	REAL,
	"Manufacturing4"	REAL,
	"Manufacturing5"	REAL,
	"Manufacturing6"	REAL,
	"Manufacturing7"	REAL,
	"Manufacturing8"	REAL,
	"Manufacturing9"	REAL,
	"Manufacturing10"	REAL,
	"Manufacturing11"	REAL,
	"Manufacturing12"	REAL,
	"Manufacturing13"	REAL,
	"Manufacturing14"	REAL,
	"Manufacturing15"	REAL,
	"Mounting"	REAL,
	"Mounting2"	REAL,
	"Dismantling"	REAL,
	"JobPlanning"	REAL,
	"JobPlanning2"	REAL,
	"JobPlanning3"	REAL,
	"Sealing"	REAL,
	"Taping"	REAL,
	"ColorBase"	TEXT,
	"ColorBase_Long"	TEXT,
	"ColorInsertions"	TEXT,
	"ColorInsertions_Long"	TEXT,
	"CEText"	TEXT,
	"CalculationComment"	TEXT,
	"MountingComment"	TEXT,
	"OfferComment"	TEXT,
	"OrderComment"	TEXT,
	"DeliveryComment"	TEXT,
	"CrossSectionComment"	TEXT,
	"InvoiceComment"	TEXT,
	"MESComment"	TEXT,
	"TextPosPicture"	TEXT,
	"ActiveTitle"	TEXT,
	"Units"	TEXT,
	"TextPosNoQuotation"	INTEGER DEFAULT 0,
	"ColorBaseRGB1"	INTEGER,
	"ColorWindowRGB1"	INTEGER,
	"ColorDoorRGB1"	INTEGER,
	"ColorBaseRGB2"	INTEGER,
	"ColorWindowRGB2"	INTEGER,
	"ColorDoorRGB2"	INTEGER,
	"HasDoors"	INTEGER DEFAULT 0,
	"HasSliders"	INTEGER DEFAULT 0,
	"Status"	INTEGER,
	"JustDoorpackage"	INTEGER DEFAULT 0,
	"SegmentGUID"	TEXT,
	"HasEnergyLabel"	INTEGER DEFAULT 0,
	"EnergyLabelAllowed"	INTEGER DEFAULT 0,
	"HistoryGroupId"	INTEGER,
	"WarningLevel"	INTEGER,
	"EnergyLabelErrCode"	INTEGER,
	"HistoryDate"	TEXT,
	"HistoryComment"	TEXT,
	"SurfaceWastage"	REAL,
	"AccessorieWastage"	REAL,
	"CoatingWastage"	REAL,
	"HardwareWastage"	REAL,
	"ProfileWastage"	REAL,
	"WoddenProfileWastage"	REAL,
	"JustReplacePackage"	INTEGER DEFAULT 0,
	"FixedPriceTotal"	REAL,
	"FixedPriceGlass"	REAL,
	"HistoryPhase"	INTEGER,
	"HasWindows"	INTEGER DEFAULT 0,
	"SubId"	INTEGER,
	"GroupId"	INTEGER,
	"UseLabourTimeSuggestion"	INTEGER DEFAULT 0,
	"SubStructureSegmentType"	INTEGER,
	"InsideOutSideSegmentType"	INTEGER,
	"ColorBaseLongInfo"	TEXT,
	"ColorInsertionsLongInfo"	TEXT,
	"FireProtectionClass"	INTEGER,
	"FireProtectionDuration"	INTEGER,
	"IsArchedOrSlanted"	INTEGER DEFAULT 0,
	"IsFreeCad"	INTEGER DEFAULT 0,
	"HasAlignedProfiles"	INTEGER DEFAULT 0,
	"LK_VATRateId"	INTEGER NOT NULL,
	"ScrewInfluenceAddition"	REAL,
	"ScrewInfluenceAddition_Output"	REAL,
	"ScrewInfluenceAddition_Unit"	TEXT,
	"IsSmokeProtection"	INTEGER DEFAULT 0,
	"IsInsertionElement"	INTEGER DEFAULT 0,
	"DatasafeQrCode"	TEXT,
	"BaseElementGUID"	TEXT,
	"LastGUID"	TEXT,
	"DoorpackageExplodeOption"	INTEGER,
	"HorizontalCrossSectionCutPicture_File"	TEXT,
	"HorizontalCrossSectionCutPicture_WidthMM"	REAL,
	"HorizontalCrossSectionCutPicture_HeightMM"	REAL,
	"HorizontalCrossSectionCutPicture_Scale"	REAL,
	"HorizontalCrossSectionCutPicture_Inside"	INTEGER,
	"HorizontalCrossSectionCutPicture_CompCad"	BLOB,
	"VerticalCrossSectionCutPicture_File"	TEXT,
	"VerticalCrossSectionCutPicture_WidthMM"	REAL,
	"VerticalCrossSectionCutPicture_HeightMM"	REAL,
	"VerticalCrossSectionCutPicture_Scale"	REAL,
	"VerticalCrossSectionCutPicture_Inside"	INTEGER,
	"VerticalCrossSectionCutPicture_CompCad"	BLOB,
	"SteelSerieFrameCoating"	INTEGER DEFAULT 0,
	"FramePicture_File"	TEXT,
	"FramePicture_WidthMM"	REAL,
	"FramePicture_HeightMM"	REAL,
	"FramePicture_Scale"	REAL,
	"FramePicture_Inside"	INTEGER,
	"FramePicture_CompCad"	BLOB,
	"DeclarationType"	INTEGER,
	"ETA_EuropeanAssessmentDocument"	TEXT,
	"ETA_TechnicalAssessment"	TEXT,
	"ETA_TechnicalAssessmentBody"	TEXT,
	"FireProtectionUsage"	INTEGER,
	PRIMARY KEY("ElevationID"),
	FOREIGN KEY("ElevationGroupId") REFERENCES "ElevationGroups"("ElevationGroupID"),
	FOREIGN KEY("LK_VATRateId") REFERENCES "VATRates"("VATRateId")
);
CREATE TABLE IF NOT EXISTS "EstimationDiscounts" (
	"EstimationDiscountID"	INTEGER NOT NULL,
	"Name"	TEXT,
	"ByWeight"	INTEGER DEFAULT 0,
	"ByWeightPrice"	REAL,
	"ByWeightCurreny"	TEXT,
	"Discount"	REAL,
	"BaseDiscount"	REAL,
	"SurfaceDiscount"	REAL,
	"ProjectDiscount"	REAL,
	"BaseProjectDiscount"	REAL,
	"SurfaceProjectDiscount"	REAL,
	"Surcharge"	REAL,
	"BaseSurcharge"	REAL,
	"SurfaceSurcharge"	REAL,
	"MarkUp"	REAL,
	"Profit"	REAL,
	"ProjectId"	INTEGER NOT NULL,
	"DiscountGroup"	TEXT,
	PRIMARY KEY("EstimationDiscountID"),
	FOREIGN KEY("ProjectId") REFERENCES "Projects"("ProjectID")
);
CREATE TABLE IF NOT EXISTS "EstimationSurcharges" (
	"EstimationSurchargeID"	INTEGER NOT NULL,
	"ProjectId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"SurchargeType"	INTEGER,
	"Price"	REAL,
	"PriceCurrency"	TEXT,
	"Unit"	TEXT,
	PRIMARY KEY("EstimationSurchargeID"),
	FOREIGN KEY("ProjectId") REFERENCES "Projects"("ProjectID")
);
CREATE TABLE IF NOT EXISTS "ExternalMonitoring" (
	"Id"	INTEGER NOT NULL,
	"Certification"	TEXT,
	"Supplier"	TEXT,
	"System"	TEXT,
	"SubSystem"	TEXT,
	"RulePackage"	TEXT,
	"NotifiedBody"	TEXT,
	"NotifiedBodyId"	TEXT,
	"Certificate"	TEXT,
	"StandardizationNumber"	TEXT,
	"CertificationYear"	INTEGER,
	PRIMARY KEY("Id")
);
CREATE TABLE IF NOT EXISTS "FreeTextNames" (
	"FreeTextNameID"	INTEGER NOT NULL,
	"Name"	TEXT,
	PRIMARY KEY("FreeTextNameID")
);
CREATE TABLE IF NOT EXISTS "GasketFrames" (
	"GasketFrameID"	INTEGER NOT NULL,
	"InsertionId"	INTEGER NOT NULL,
	"LK_KfmKeyId"	INTEGER,
	"LK_SupplierId"	INTEGER NOT NULL,
	"LK_ManufacturerId"	INTEGER,
	"LK_DiscountId"	INTEGER,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"xSashGUID"	TEXT,
	"Amount"	INTEGER,
	"Layer"	INTEGER,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"FieldNo"	INTEGER,
	"Len1"	REAL,
	"Len1_Output"	REAL,
	"Len1_Unit"	TEXT,
	"Len2"	REAL,
	"Len2_Output"	REAL,
	"Len2_Unit"	TEXT,
	"Gasket1"	TEXT,
	"Gasket1_Supplier"	TEXT,
	"Gasket1_Number"	TEXT,
	"Gasket1_BaseNumber"	TEXT,
	"Gasket1_OrderCode"	TEXT,
	"Gasket1_OriginalNumber"	TEXT,
	"Gasket2"	TEXT,
	"Gasket2_Supplier"	TEXT,
	"Gasket2_Number"	TEXT,
	"Gasket2_BaseNumber"	TEXT,
	"Gasket2_OrderCode"	TEXT,
	"Gasket2_OriginalNumber"	TEXT,
	"FrameType"	INTEGER,
	"Price"	REAL,
	"PriceGross"	REAL,
	"Discount"	REAL,
	"PUSize"	REAL,
	"PUSize_Output"	REAL,
	"PUSize_Unit"	TEXT,
	"SubSize"	REAL,
	"ArticleType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"ProcessingPoint"	TEXT,
	"ProcessingPointType"	INTEGER,
	"ProductGroup"	TEXT,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"Picture17_File"	TEXT,
	"Picture17_WidthMM"	REAL,
	"Picture17_HeightMM"	REAL,
	"Picture17_Scale"	REAL,
	"Picture17_Inside"	INTEGER,
	"Picture17_CompCad"	BLOB,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	"SubNo"	INTEGER,
	"PosAndFieldAssignmend"	TEXT,
	"TrilateralGasketFramePicture_File"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	PRIMARY KEY("GasketFrameID"),
	FOREIGN KEY("InsertionId") REFERENCES "Insertions"("InsertionID"),
	FOREIGN KEY("LK_SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "GeorgianBars" (
	"GeorgianBarsID"	INTEGER NOT NULL,
	"GlassId"	INTEGER NOT NULL,
	"LK_SupplierId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"Amount"	INTEGER,
	"SpacerAmount"	INTEGER,
	"Orientation"	TEXT,
	"Description"	TEXT,
	"Description2"	TEXT,
	"BarType"	INTEGER,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"BarSize"	REAL,
	"BarSize_Output"	REAL,
	"BarSize_Unit"	TEXT,
	"FullProfile"	INTEGER DEFAULT 0,
	"Position1"	REAL,
	"Position1_Output"	REAL,
	"Position1_Unit"	TEXT,
	"BarNumber"	INTEGER,
	"StartX"	REAL,
	"StartX_Output"	REAL,
	"StartX_Unit"	TEXT,
	"StartY"	REAL,
	"StartY_Output"	REAL,
	"StartY_Unit"	TEXT,
	"EndX"	REAL,
	"EndX_Output"	REAL,
	"EndX_Unit"	TEXT,
	"EndY"	REAL,
	"EndY_Output"	REAL,
	"EndY_Unit"	TEXT,
	PRIMARY KEY("GeorgianBarsID"),
	FOREIGN KEY("GlassId") REFERENCES "Glass"("GlassID"),
	FOREIGN KEY("LK_SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "Glass" (
	"GlassID"	INTEGER NOT NULL,
	"LK_SupplierId"	INTEGER NOT NULL,
	"LK_DiscountId"	INTEGER,
	"InsertionId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"Description"	TEXT,
	"VariantDescription"	TEXT,
	"Comment1"	TEXT,
	"Comment2"	TEXT,
	"NameShort"	TEXT,
	"xGUID"	TEXT,
	"HashCode"	TEXT,
	"xSashGUID"	TEXT,
	"Middle"	TEXT,
	"Configuration"	TEXT,
	"Info1"	TEXT,
	"Info2"	TEXT,
	"AdditionalInformation"	TEXT,
	"InfoDrawing"	TEXT,
	"Price"	REAL,
	"PriceGross"	REAL,
	"SurchargePc"	REAL,
	"SurchargeKG"	REAL,
	"SurchargeM2"	REAL,
	"SurchargePerc"	REAL,
	"ArtNo"	TEXT,
	"InsertionNo"	INTEGER,
	"InsertionSubno"	INTEGER,
	"Origin"	TEXT,
	"AreaOffer"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"WidthFilling"	REAL,
	"WidthFilling_Output"	REAL,
	"WidthFilling_Unit"	TEXT,
	"HeightFilling"	REAL,
	"HeightFilling_Output"	REAL,
	"HeightFilling_Unit"	TEXT,
	"WidthGridPrices"	REAL,
	"WidthGridPrices_Output"	REAL,
	"WidthGridPrices_Unit"	TEXT,
	"HeightGridPrices"	REAL,
	"HeightGridPrices_Output"	REAL,
	"HeightGridPrices_Unit"	TEXT,
	"WidthEstimation"	REAL,
	"WidthEstimation_Output"	REAL,
	"WidthEstimation_Unit"	TEXT,
	"HeightEstimation"	REAL,
	"HeightEstimation_Output"	REAL,
	"HeightEstimation_Unit"	TEXT,
	"WidthStepInside"	REAL,
	"WidthStepInside_Output"	REAL,
	"WidthStepInside_Unit"	TEXT,
	"HeightStepInside"	REAL,
	"HeightStepInside_Output"	REAL,
	"HeightStepInside_Unit"	TEXT,
	"WidthStepOutside"	REAL,
	"WidthStepOutside_Output"	REAL,
	"WidthStepOutside_Unit"	TEXT,
	"HeightStepOutside"	REAL,
	"HeightStepOutside_Output"	REAL,
	"HeightStepOutside_Unit"	TEXT,
	"Strength"	REAL,
	"Strength_Output"	REAL,
	"Strength_Unit"	TEXT,
	"ActualStrength"	REAL,
	"ActualStrength_Output"	REAL,
	"ActualStrength_Unit"	TEXT,
	"SlideInLeft"	REAL,
	"SlideInLeft_Output"	REAL,
	"SlideInLeft_Unit"	TEXT,
	"SlideInRight"	REAL,
	"SlideInRight_Output"	REAL,
	"SlideInRight_Unit"	TEXT,
	"SlideInTop"	REAL,
	"SlideInTop_Output"	REAL,
	"SlideInTop_Unit"	TEXT,
	"SlideInBottom"	REAL,
	"SlideInBottom_Output"	REAL,
	"SlideInBottom_Unit"	TEXT,
	"AreaQM"	REAL,
	"AreaQM_Output"	REAL,
	"AreaQM_Unit"	TEXT,
	"AreaEstimationQM"	REAL,
	"AreaEstimationQM_Output"	REAL,
	"AreaEstimationQM_Unit"	TEXT,
	"VisibleArea"	REAL,
	"VisibleArea_Output"	REAL,
	"VisibleArea_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"PerimeterStep"	REAL,
	"PerimeterStep_Output"	REAL,
	"PerimeterStep_Unit"	TEXT,
	"ModelType"	INTEGER,
	"GlassType"	TEXT,
	"Amount"	INTEGER,
	"FieldNo"	INTEGER,
	"Inside"	TEXT,
	"Outside"	TEXT,
	"UValue"	REAL,
	"UValue_Output"	REAL,
	"UValue_Unit"	TEXT,
	"PsiValue"	REAL,
	"PsiValue_Output"	REAL,
	"PsiValue_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"SpecialAllowed"	INTEGER DEFAULT 0,
	"HasGeorgianBars"	INTEGER DEFAULT 0,
	"MinSpacerGap"	REAL,
	"MaxSpacerGap"	REAL,
	"SpacerGap"	REAL,
	"SpacerGap_Output"	REAL,
	"SpacerGap_Unit"	TEXT,
	"StrengthI"	REAL,
	"StrengthI_Output"	REAL,
	"StrengthI_Unit"	TEXT,
	"StrengthM"	REAL,
	"StrengthM_Output"	REAL,
	"StrengthM_Unit"	TEXT,
	"SpacerGap2"	REAL,
	"SpacerGap2_Output"	REAL,
	"SpacerGap2_Unit"	TEXT,
	"StrengthO"	REAL,
	"StrengthO_Output"	REAL,
	"StrengthO_Unit"	TEXT,
	"Picture9_File"	TEXT,
	"Picture9_WidthMM"	REAL,
	"Picture9_HeightMM"	REAL,
	"Picture9_Scale"	REAL,
	"Picture9_Inside"	INTEGER,
	"Picture9_CompCad"	BLOB,
	"Picture10_File"	TEXT,
	"Picture10_WidthMM"	REAL,
	"Picture10_HeightMM"	REAL,
	"Picture10_Scale"	REAL,
	"Picture10_Inside"	INTEGER,
	"Picture10_CompCad"	BLOB,
	"StepGlasPicture_File"	TEXT,
	"StepGlasPicture_WidthMM"	REAL,
	"StepGlasPicture_HeightMM"	REAL,
	"StepGlasPicture_Scale"	REAL,
	"StepGlasPicture_Inside"	INTEGER,
	"StepGlasPicture_CompCad"	BLOB,
	"InnerPanelColor"	TEXT,
	"OuterPanelColor"	TEXT,
	"RatedAcousticReductionIndex"	REAL,
	"RatedAcousticReductionIndexC"	INTEGER,
	"RatedAcousticReductionIndexCtr"	INTEGER,
	"TotalEnergyTransmittance"	REAL,
	"SolarFactor"	REAL,
	"TypeOfSpacer"	TEXT,
	"TypeOfSpacerEnum"	INTEGER,
	"Productgroup"	TEXT,
	"ShapedGlassDrawing"	TEXT,
	"ProcessingPointType"	INTEGER,
	"OfferText"	TEXT,
	"PictureDoorFilling_File"	TEXT,
	"PictureDoorFilling_WidthMM"	REAL,
	"PictureDoorFilling_HeightMM"	REAL,
	"PictureDoorFilling_Scale"	REAL,
	"PictureDoorFilling_Inside"	INTEGER,
	"PictureDoorFilling_CompCad"	BLOB,
	PRIMARY KEY("GlassID"),
	FOREIGN KEY("InsertionId") REFERENCES "Insertions"("InsertionID"),
	FOREIGN KEY("LK_SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "GlassBarcodes" (
	"GlassBarcodeId"	INTEGER NOT NULL,
	"Barcode"	TEXT,
	"GlassId"	INTEGER NOT NULL,
	PRIMARY KEY("GlassBarcodeId"),
	FOREIGN KEY("GlassId") REFERENCES "Glass"("GlassID")
);
CREATE TABLE IF NOT EXISTS "GlassPieces" (
	"GlassPieceID"	INTEGER NOT NULL,
	"Name"	TEXT,
	"GlassId"	INTEGER NOT NULL,
	"xGUID"	TEXT,
	"Location"	INTEGER,
	"GlassKind"	INTEGER,
	"GlassType"	TEXT,
	"Strength"	REAL,
	"Strength_Output"	REAL,
	"Strength_Unit"	TEXT,
	"GasFillingType1"	INTEGER,
	"GasFillingType2"	INTEGER,
	"GasFillingRatio1"	REAL,
	"GasFillingRatio2"	REAL,
	"FoilPosition"	INTEGER,
	"Price"	REAL,
	"PriceValid"	INTEGER DEFAULT 0,
	PRIMARY KEY("GlassPieceID"),
	FOREIGN KEY("GlassId") REFERENCES "Glass"("GlassID")
);
CREATE TABLE IF NOT EXISTS "InsertionWarnings" (
	"InsertionWarningID"	INTEGER NOT NULL,
	"InsertionId"	INTEGER NOT NULL,
	"Information"	TEXT,
	"Type"	INTEGER,
	"ShowHintInEstimation"	INTEGER DEFAULT 0,
	"ShowHintInAssemblyList"	INTEGER DEFAULT 0,
	"ShowHintInGlassOrder"	INTEGER DEFAULT 0,
	PRIMARY KEY("InsertionWarningID"),
	FOREIGN KEY("InsertionId") REFERENCES "Insertions"("InsertionID")
);
CREATE TABLE IF NOT EXISTS "Insertions" (
	"InsertionID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"InsertionNo"	INTEGER,
	"ParentInsertion"	INTEGER,
	"xGUID"	TEXT,
	"xSegmentGUID"	TEXT,
	"GroupID"	INTEGER,
	"TypeNr"	INTEGER,
	"AmountSashes"	INTEGER,
	"Description"	TEXT,
	"Type"	TEXT,
	"DIN"	TEXT,
	"Info"	TEXT,
	"Material"	TEXT,
	"BarcodePRS"	TEXT,
	"BarcodeFPMMain"	TEXT,
	"BarcodeFPMSlave"	TEXT,
	"BarcodeRuchserMain"	TEXT,
	"BarcodeRuchserSlave"	TEXT,
	"BarcodeSC_LA_100Main"	TEXT,
	"BarcodeSC_LA_100Slave"	TEXT,
	"BarcodeSC_PrsFrMain"	TEXT,
	"BarcodeSC_PrsFrSlave"	TEXT,
	"BarcodeSC_SPTMain"	TEXT,
	"BarcodeSC_SPTSlave"	TEXT,
	"HardwareSet"	TEXT,
	"HardwareSet_Supplier"	TEXT,
	"HardwareSet_Number"	TEXT,
	"HardwareSet_BaseNumber"	TEXT,
	"HardwareSet_OrderCode"	TEXT,
	"HardwareSet_OriginalNumber"	TEXT,
	"HardwareColor"	TEXT,
	"HardwareSelection1Caption"	TEXT,
	"HardwareSelection1Value"	TEXT,
	"HardwareSelection1Color"	TEXT,
	"Sub1Color"	TEXT,
	"Sub1ColorRGBI"	INTEGER,
	"Sub1ColorRGBA"	INTEGER,
	"HardwareSelection2Caption"	TEXT,
	"HardwareSelection2Value"	TEXT,
	"HardwareSelection2Color"	TEXT,
	"Sub2Color"	TEXT,
	"Sub2ColorRGBI"	INTEGER,
	"Sub2ColorRGBA"	INTEGER,
	"HardwareSelection3Caption"	TEXT,
	"HardwareSelection3Value"	TEXT,
	"HardwareSelection3Color"	TEXT,
	"Sub3Color"	TEXT,
	"Sub3ColorRGBI"	INTEGER,
	"Sub3ColorRGBA"	INTEGER,
	"HardwareSelection4Caption"	TEXT,
	"HardwareSelection4Value"	TEXT,
	"HardwareSelection4Color"	TEXT,
	"Sub4Color"	TEXT,
	"Sub4ColorRGBI"	INTEGER,
	"Sub4ColorRGBA"	INTEGER,
	"HardwareSelection5Caption"	TEXT,
	"HardwareSelection5Value"	TEXT,
	"HardwareSelection5Color"	TEXT,
	"Sub5Color"	TEXT,
	"Sub5ColorRGBI"	INTEGER,
	"Sub5ColorRGBA"	INTEGER,
	"HardwareSelection6Caption"	TEXT,
	"HardwareSelection6Value"	TEXT,
	"HardwareSelection6Color"	TEXT,
	"Sub6Color"	TEXT,
	"Sub6ColorRGBI"	INTEGER,
	"Sub6ColorRGBA"	INTEGER,
	"HardwareSelection7Caption"	TEXT,
	"HardwareSelection7Value"	TEXT,
	"HardwareSelection7Color"	TEXT,
	"Sub7Color"	TEXT,
	"Sub7ColorRGBI"	INTEGER,
	"Sub7ColorRGBA"	INTEGER,
	"HardwareSelection8Caption"	TEXT,
	"HardwareSelection8Value"	TEXT,
	"HardwareSelection8Color"	TEXT,
	"Sub8Color"	TEXT,
	"Sub8ColorRGBI"	INTEGER,
	"Sub8ColorRGBA"	INTEGER,
	"HardwareSelection9Caption"	TEXT,
	"HardwareSelection9Value"	TEXT,
	"HardwareSelection9Color"	TEXT,
	"Sub9Color"	TEXT,
	"Sub9ColorRGBI"	INTEGER,
	"Sub9ColorRGBA"	INTEGER,
	"HardwareSelection10Caption"	TEXT,
	"HardwareSelection10Value"	TEXT,
	"HardwareSelection10Color"	TEXT,
	"Sub10Color"	TEXT,
	"Sub10ColorRGBI"	INTEGER,
	"Sub10ColorRGBA"	INTEGER,
	"BottomConfigType"	TEXT,
	"BottomConfigName"	TEXT,
	"BottomConfigInfo"	TEXT,
	"GapDoor"	REAL,
	"GapDoor_Output"	REAL,
	"GapDoor_Unit"	TEXT,
	"OffsetDoor"	REAL,
	"OffsetDoor_Output"	REAL,
	"OffsetDoor_Unit"	TEXT,
	"FloorRecess"	REAL,
	"FloorRecess_Output"	REAL,
	"FloorRecess_Unit"	TEXT,
	"GapSide"	REAL,
	"GapSide_Output"	REAL,
	"GapSide_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"WidthGridPrices"	REAL,
	"WidthGridPrices_Output"	REAL,
	"WidthGridPrices_Unit"	TEXT,
	"HeightGridPrices"	REAL,
	"HeightGridPrices_Output"	REAL,
	"HeightGridPrices_Unit"	TEXT,
	"Width2"	REAL,
	"Width2_Output"	REAL,
	"Width2_Unit"	TEXT,
	"Height2"	REAL,
	"Height2_Output"	REAL,
	"Height2_Unit"	TEXT,
	"MasterLeaf"	INTEGER,
	"HandleHeight"	REAL,
	"HandleHeight_Output"	REAL,
	"HandleHeight_Unit"	TEXT,
	"HandleHeightReference"	INTEGER,
	"HandleInMid"	INTEGER DEFAULT 0,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"SightSizeWidth"	REAL,
	"SightSizeWidth_Output"	REAL,
	"SightSizeWidth_Unit"	TEXT,
	"SightSizeHeight"	REAL,
	"SightSizeHeight_Output"	REAL,
	"SightSizeHeight_Unit"	TEXT,
	"SightSizeDoorClearance"	REAL,
	"SightSizeDoorClearance_Output"	REAL,
	"SightSizeDoorClearance_Unit"	TEXT,
	"SightSizeDoorClearanceGap"	REAL,
	"SightSizeDoorClearanceGap_Output"	REAL,
	"SightSizeDoorClearanceGap_Unit"	TEXT,
	"SightSizeDoorClearanceMaster"	REAL,
	"SightSizeDoorClearanceMaster_Output"	REAL,
	"SightSizeDoorClearanceMaster_Unit"	TEXT,
	"SightSizeDoorClearanceMasterGap"	REAL,
	"SightSizeDoorClearanceMasterGap_Output"	REAL,
	"SightSizeDoorClearanceMasterGap_Unit"	TEXT,
	"IsPrepared"	INTEGER DEFAULT 0,
	"IsSubPos"	INTEGER DEFAULT 0,
	"PreparedDepthInside"	REAL,
	"PreparedDepthInside_Output"	REAL,
	"PreparedDepthInside_Unit"	TEXT,
	"PreparedDepthOutside"	REAL,
	"PreparedDepthOutside_Output"	REAL,
	"PreparedDepthOutside_Unit"	TEXT,
	"IsPrepared2"	INTEGER DEFAULT 0,
	"PreparedDepthInside2"	REAL,
	"PreparedDepthInside2_Output"	REAL,
	"PreparedDepthInside2_Unit"	TEXT,
	"PreparedDepthOutside2"	REAL,
	"PreparedDepthOutside2_Output"	REAL,
	"PreparedDepthOutside2_Unit"	TEXT,
	"IsPrepared3"	INTEGER DEFAULT 0,
	"PreparedDepthInside3"	REAL,
	"PreparedDepthInside3_Output"	REAL,
	"PreparedDepthInside3_Unit"	TEXT,
	"PreparedDepthOutside3"	REAL,
	"PreparedDepthOutside3_Output"	REAL,
	"PreparedDepthOutside3_Unit"	TEXT,
	"SubPosValid"	INTEGER DEFAULT 0,
	"DoorpackPictureI_File"	TEXT,
	"DoorpackPictureI_WidthMM"	REAL,
	"DoorpackPictureI_HeightMM"	REAL,
	"DoorpackPictureI_Scale"	REAL,
	"DoorpackPictureI_Inside"	INTEGER,
	"DoorpackPictureI_CompCad"	BLOB,
	"DoorpackPictureO_File"	TEXT,
	"DoorpackPictureO_WidthMM"	REAL,
	"DoorpackPictureO_HeightMM"	REAL,
	"DoorpackPictureO_Scale"	REAL,
	"DoorpackPictureO_Inside"	INTEGER,
	"DoorpackPictureO_CompCad"	BLOB,
	"InsertionPicture_File"	TEXT,
	"InsertionPicture_WidthMM"	REAL,
	"InsertionPicture_HeightMM"	REAL,
	"InsertionPicture_Scale"	REAL,
	"InsertionPicture_Inside"	INTEGER,
	"InsertionPicture_CompCad"	BLOB,
	"EscapeDoorInOpeningDirection"	INTEGER DEFAULT 0,
	"IOMasterLeafEscapeDoortype"	INTEGER,
	"IOSlaveLeafEscapeDoortype"	INTEGER,
	"EscapeDoorAgainstOpeningDirection"	INTEGER DEFAULT 0,
	"AOMasterLeafEscapeDoortype"	INTEGER,
	"HandleHeightDriveBolt"	REAL,
	"HandleHeightDriveBolt_Output"	REAL,
	"HandleHeightDriveBolt_Unit"	TEXT,
	PRIMARY KEY("InsertionID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "KfmKeys" (
	"KfmKeyID"	INTEGER NOT NULL,
	"KfmKey"	TEXT,
	PRIMARY KEY("KfmKeyID")
);
CREATE TABLE IF NOT EXISTS "LabourCosts" (
	"LabourCostsId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Type"	INTEGER,
	"Name"	TEXT,
	"Price"	REAL,
	"TimeReduction"	REAL,
	"Show"	INTEGER DEFAULT 0,
	"DontMultiplyWithPosQty"	INTEGER DEFAULT 0,
	PRIMARY KEY("LabourCostsId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "LabourTimes" (
	"LabourTimeId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"TimeNr"	INTEGER,
	"TimeType"	INTEGER,
	"Amount"	INTEGER,
	"What"	INTEGER,
	"TimeId"	INTEGER,
	"TotalMinutes"	REAL,
	"SingleMinutes"	REAL,
	"Comment"	TEXT,
	"WhatName"	TEXT,
	"Name"	TEXT,
	"IsMain"	INTEGER DEFAULT 0,
	PRIMARY KEY("LabourTimeId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "Manufacturers" (
	"ManufacturersID"	INTEGER NOT NULL,
	"ShortName"	TEXT,
	"Name"	TEXT,
	"Description"	TEXT,
	"PriceLevel"	TEXT,
	"ArticleLevel"	TEXT,
	"PriceVariantName"	TEXT,
	"DBVersion"	INTEGER,
	"CADVersion"	INTEGER,
	"ExpirationDate"	TEXT,
	"ManuCurrency"	TEXT,
	"ArticleNumberDisplayOption"	INTEGER,
	PRIMARY KEY("ManufacturersID")
);
CREATE TABLE IF NOT EXISTS "MbioeAreas" (
	"MbioeAreaId"	INTEGER NOT NULL,
	"MbioeTreeId"	INTEGER NOT NULL,
	"Name"	TEXT,
	PRIMARY KEY("MbioeAreaId"),
	FOREIGN KEY("MbioeTreeId") REFERENCES "MbioeTrees"("MbioeTreeId")
);
CREATE TABLE IF NOT EXISTS "MbioeControls" (
	"MbioeControlId"	INTEGER NOT NULL,
	"MbioeAreaId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"Tag"	INTEGER,
	"Picture"	TEXT,
	PRIMARY KEY("MbioeControlId"),
	FOREIGN KEY("MbioeAreaId") REFERENCES "MbioeAreas"("MbioeAreaId")
);
CREATE TABLE IF NOT EXISTS "MbioeElevations" (
	"MbioeElevationId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"ElementPricelistGuid"	TEXT,
	"Name"	TEXT,
	"Picture"	TEXT,
	"InFolder"	TEXT,
	"OfferText"	TEXT,
	PRIMARY KEY("MbioeElevationId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "MbioeItems" (
	"MbioeItemId"	INTEGER NOT NULL,
	"MbioeControlId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"OfferPrice"	REAL,
	"ShowPrice"	INTEGER DEFAULT 0,
	"ShowText"	INTEGER,
	"Picture"	TEXT,
	PRIMARY KEY("MbioeItemId"),
	FOREIGN KEY("MbioeControlId") REFERENCES "MbioeControls"("MbioeControlId")
);
CREATE TABLE IF NOT EXISTS "MbioeTags" (
	"MbioeTagId"	INTEGER NOT NULL,
	"Name"	TEXT,
	PRIMARY KEY("MbioeTagId")
);
CREATE TABLE IF NOT EXISTS "MbioeTrees" (
	"MbioeTreeId"	INTEGER NOT NULL,
	"MbioeElevationId"	INTEGER NOT NULL,
	"Type"	TEXT,
	PRIMARY KEY("MbioeTreeId"),
	FOREIGN KEY("MbioeElevationId") REFERENCES "MbioeElevations"("MbioeElevationId")
);
CREATE TABLE IF NOT EXISTS "MountingLines" (
	"MountingLineID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Orientation"	INTEGER,
	"Frame0"	INTEGER DEFAULT 0,
	"Frame1"	INTEGER DEFAULT 0,
	"Door"	INTEGER DEFAULT 0,
	"Window"	INTEGER DEFAULT 0,
	"InsideView"	INTEGER DEFAULT 0,
	"X0"	REAL,
	"Y0"	REAL,
	"X1"	REAL,
	"Y1"	REAL,
	"ElevationGUID"	TEXT,
	PRIMARY KEY("MountingLineID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "Phases" (
	"PhaseID"	INTEGER NOT NULL,
	"Name"	TEXT,
	"Info1"	TEXT,
	"Info2"	TEXT,
	"Info3"	TEXT,
	"xGUID"	TEXT,
	"ProjectId"	INTEGER NOT NULL,
	PRIMARY KEY("PhaseID"),
	FOREIGN KEY("ProjectId") REFERENCES "Projects"("ProjectID")
);
CREATE TABLE IF NOT EXISTS "ProfileBars" (
	"ProfileBarID"	INTEGER NOT NULL,
	"SupplierId"	INTEGER NOT NULL,
	"LK_KfmKeyId"	INTEGER,
	"LK_ManufacturerId"	INTEGER,
	"LK_ColorId"	INTEGER,
	"LK_InnerColorId"	INTEGER NOT NULL,
	"LK_OuterColorId"	INTEGER NOT NULL,
	"LK_DiscountId"	INTEGER,
	"LK_SawId"	INTEGER,
	"xGUID"	TEXT,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"IsManual"	INTEGER DEFAULT 0,
	"IsInactive"	INTEGER DEFAULT 0,
	"Color"	TEXT,
	"InnerColor"	TEXT,
	"OuterColor"	TEXT,
	"IsDualColor"	INTEGER DEFAULT 0,
	"PieceListType"	INTEGER,
	"ColorTypeInternal"	INTEGER,
	"ColorInfoInternal"	TEXT,
	"ColorDescription"	TEXT,
	"InnerColorTypeInternal"	INTEGER,
	"InnerColorInfoInternal"	TEXT,
	"OuterColorTypeInternal"	INTEGER,
	"OuterColorInfoInternal"	TEXT,
	"ColorCombinationGUID"	TEXT,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"UsedLength"	REAL,
	"UsedLength_Output"	REAL,
	"UsedLength_Unit"	TEXT,
	"LeftOver"	REAL,
	"LeftOver_Output"	REAL,
	"LeftOver_Unit"	TEXT,
	"Amount"	INTEGER,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"IsArched"	INTEGER DEFAULT 0,
	"IsResidualLength"	INTEGER DEFAULT 0,
	"IsFixedLength"	INTEGER DEFAULT 0,
	"FixSurcharge"	REAL,
	"IsSpecialLength"	INTEGER DEFAULT 0,
	"ResidualIgnored"	INTEGER DEFAULT 0,
	"SawCut"	REAL,
	"SawCut_Output"	REAL,
	"SawCut_Unit"	TEXT,
	"EndCut"	REAL,
	"EndCut_Output"	REAL,
	"EndCut_Unit"	TEXT,
	"MinUsableLen"	REAL,
	"MinUsableLen_Output"	REAL,
	"MinUsableLen_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"PerimeterBoundaryBox"	REAL,
	"PerimeterBoundaryBox_Output"	REAL,
	"PerimeterBoundaryBox_Unit"	TEXT,
	"VisibleSurface"	REAL,
	"VisibleSurface_Output"	REAL,
	"VisibleSurface_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Discount"	REAL,
	"Price"	REAL,
	"PriceGross"	REAL,
	"PriceCoating"	REAL,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"SupplierCode"	INTEGER,
	"PUSize"	REAL,
	"PUSize_Output"	REAL,
	"PUSize_Unit"	TEXT,
	"SubSize"	REAL,
	"ArticleType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"ProcessingPoint"	TEXT,
	"ProcessingPointType"	INTEGER,
	"ProductGroup"	TEXT,
	"Picture11_File"	TEXT,
	"Picture11_WidthMM"	REAL,
	"Picture11_HeightMM"	REAL,
	"Picture11_Scale"	REAL,
	"Picture11_Inside"	INTEGER,
	"Picture11_CompCad"	BLOB,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"Picture16_File"	TEXT,
	"Picture16_WidthMM"	REAL,
	"Picture16_HeightMM"	REAL,
	"Picture16_Scale"	REAL,
	"Picture16_Inside"	INTEGER,
	"Picture16_CompCad"	BLOB,
	"DoubleCuts"	INTEGER DEFAULT 0,
	"ProfileCostOrdered"	REAL,
	"ProfileCostNeeded"	REAL,
	"ProfileCostUsed"	REAL,
	"CoatingCostOrdered"	REAL,
	"CoatingCostNeeded"	REAL,
	"CoatingCostUsed"	REAL,
	"CoatedPCostOrdered"	REAL,
	"CoatedPCostNeeded"	REAL,
	"CoatedPCostUsed"	REAL,
	"CuttingLossMR"	REAL,
	"CuttingLossMR_Output"	REAL,
	"CuttingLossMR_Unit"	TEXT,
	"CuttingLossOR"	REAL,
	"CuttingLossOR_Output"	REAL,
	"CuttingLossOR_Unit"	TEXT,
	"Residuallength"	REAL,
	"Residuallength_Output"	REAL,
	"Residuallength_Unit"	TEXT,
	"RealUsedLength"	REAL,
	"RealUsedLength_Output"	REAL,
	"RealUsedLength_Unit"	TEXT,
	"CuttingLoss"	REAL,
	"CuttingLoss_Output"	REAL,
	"CuttingLoss_Unit"	TEXT,
	"CalculationSurcharge"	REAL,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	"IsDual"	INTEGER DEFAULT 0,
	"RowForSawFile"	TEXT,
	"WoodType"	INTEGER,
	"WoodTypeDescription"	TEXT,
	"CoatingColor"	INTEGER DEFAULT 0,
	"Material"	INTEGER,
	"MaterialDescription"	TEXT,
	"CompoundMarkerColor"	TEXT,
	"CompoundMarkerMaterial"	TEXT,
	"ArticleTypePrintout"	INTEGER,
	"SequentialNumber"	INTEGER,
	PRIMARY KEY("ProfileBarID"),
	FOREIGN KEY("LK_InnerColorId") REFERENCES "Colors"("ColorID"),
	FOREIGN KEY("LK_OuterColorId") REFERENCES "Colors"("ColorID"),
	FOREIGN KEY("SupplierId") REFERENCES "Suppliers"("SupplierID")
);
CREATE TABLE IF NOT EXISTS "ProfileCNCs" (
	"ProfileCNCID"	INTEGER NOT NULL,
	"ProfileId"	INTEGER NOT NULL,
	"LK_SawId"	INTEGER,
	"CNC"	TEXT,
	"CNCOrder"	INTEGER,
	"CNCType"	INTEGER,
	"CNCSubType"	INTEGER,
	PRIMARY KEY("ProfileCNCID"),
	FOREIGN KEY("ProfileId") REFERENCES "Profiles"("ProfileID")
);
CREATE TABLE IF NOT EXISTS "ProfileCuts" (
	"ProfileCutID"	INTEGER NOT NULL,
	"ProfileBarId"	INTEGER NOT NULL,
	"LK_ProfileId"	INTEGER NOT NULL,
	"Barcode"	TEXT,
	"BarcodeSC"	INTEGER,
	"Instance"	INTEGER,
	"PVCTrolley"	INTEGER,
	"PVCSection"	INTEGER,
	PRIMARY KEY("ProfileCutID"),
	FOREIGN KEY("LK_ProfileId") REFERENCES "Profiles"("ProfileID"),
	FOREIGN KEY("ProfileBarId") REFERENCES "ProfileBars"("ProfileBarID")
);
CREATE TABLE IF NOT EXISTS "Profiles" (
	"ProfileID"	INTEGER NOT NULL,
	"InsertionId"	INTEGER NOT NULL,
	"LK_KfmKeyId"	INTEGER,
	"LK_CalcItemNameId"	INTEGER,
	"LK_DiscountId"	INTEGER,
	"LK_ManufacturerId"	INTEGER,
	"LK_ColorId"	INTEGER,
	"LK_InnerColorId"	INTEGER,
	"LK_OuterColorId"	INTEGER,
	"LK_SupplierID"	INTEGER,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"xSegmentGUID"	TEXT,
	"xSashGUID"	TEXT,
	"xGUID"	TEXT,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"LengthOptimization"	REAL,
	"LengthOptimization_Output"	REAL,
	"LengthOptimization_Unit"	TEXT,
	"LengthAssemblyPlan"	REAL,
	"LengthAssemblyPlan_Output"	REAL,
	"LengthAssemblyPlan_Unit"	TEXT,
	"RealLength"	REAL,
	"RealLength_Output"	REAL,
	"RealLength_Unit"	TEXT,
	"RealViewLength"	REAL,
	"RealViewLength_Output"	REAL,
	"RealViewLength_Unit"	TEXT,
	"CutLeft"	REAL,
	"CutLeft_OutputVI"	TEXT,
	"CutRight"	REAL,
	"CutRight_OutputVI"	TEXT,
	"CutLeft2"	REAL,
	"CutLeft2_OutputVI"	TEXT,
	"CutRight2"	REAL,
	"CutRight2_OutputVI"	TEXT,
	"RawCutLeft"	REAL,
	"RawCutLeft_OutputVI"	TEXT,
	"RawCutRight"	REAL,
	"RawCutRight_OutputVI"	TEXT,
	"RawCutLeft2"	REAL,
	"RawCutLeft2_OutputVI"	TEXT,
	"RawCutRight2"	REAL,
	"RawCutRight2_OutputVI"	TEXT,
	"Color"	TEXT,
	"InnerColor"	TEXT,
	"OuterColor"	TEXT,
	"IsDualColor"	INTEGER DEFAULT 0,
	"ColorTypeInternal"	INTEGER,
	"ColorInfoInternal"	TEXT,
	"InnerColorTypeInternal"	INTEGER,
	"InnerColorInfoInternal"	TEXT,
	"OuterColorTypeInternal"	INTEGER,
	"OuterColorInfoInternal"	TEXT,
	"ColorCombinationGUID"	TEXT,
	"DifferentColor"	INTEGER DEFAULT 0,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"LockingBarInfo"	TEXT,
	"LockingBarPos"	TEXT,
	"LockingBarPosLong"	TEXT,
	"LockingBarPosEnum"	INTEGER,
	"NotchLeft"	REAL,
	"NotchLeft_Output"	REAL,
	"NotchLeft_Unit"	TEXT,
	"NotchRight"	REAL,
	"NotchRight_Output"	REAL,
	"NotchRight_Unit"	TEXT,
	"MinRadius"	REAL,
	"MinRadius_Output"	REAL,
	"MinRadius_Unit"	TEXT,
	"MaxRadius"	REAL,
	"MaxRadius_Output"	REAL,
	"MaxRadius_Unit"	TEXT,
	"IsArched"	INTEGER DEFAULT 0,
	"EnlargedTo"	REAL,
	"EnlargedTo_Output"	REAL,
	"EnlargedTo_Unit"	TEXT,
	"DepthEnlargedTo"	REAL,
	"DepthEnlargedTo_Output"	REAL,
	"DepthEnlargedTo_Unit"	TEXT,
	"PieceId"	INTEGER,
	"JobId"	INTEGER,
	"IntId"	TEXT,
	"AssemblyName"	TEXT,
	"AssemblyNo"	INTEGER,
	"AssemblyInfo"	TEXT,
	"AssemblyInfoNo"	INTEGER,
	"TConnLeft"	TEXT,
	"TConnRight"	TEXT,
	"MountingOrder"	INTEGER,
	"FromHardware"	INTEGER,
	"InsertionNo"	INTEGER,
	"InsertionSubNo"	INTEGER,
	"Layer"	INTEGER,
	"Price"	REAL,
	"PriceGross"	REAL,
	"IsMain"	INTEGER DEFAULT 0,
	"PriceWithCol"	INTEGER DEFAULT 0,
	"IsSalesPriceItem"	INTEGER DEFAULT 0,
	"Material"	INTEGER,
	"MaterialDescription"	TEXT,
	"ArticleType"	INTEGER,
	"PieceListType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"IsAdditional"	INTEGER DEFAULT 0,
	"IsManual"	INTEGER DEFAULT 0,
	"IsInactive"	INTEGER DEFAULT 0,
	"IsMixedPrice"	INTEGER DEFAULT 0,
	"MixedQty1"	REAL,
	"MixedQty2"	REAL,
	"ProcessingPoint"	TEXT,
	"ProcessingPointType"	INTEGER,
	"ProductGroup"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"PerimeterBoundaryBox"	REAL,
	"PerimeterBoundaryBox_Output"	REAL,
	"PerimeterBoundaryBox_Unit"	TEXT,
	"PerimeterI"	REAL,
	"PerimeterI_Output"	REAL,
	"PerimeterI_Unit"	TEXT,
	"PerimeterO"	REAL,
	"PerimeterO_Output"	REAL,
	"PerimeterO_Unit"	TEXT,
	"VisibleSurface"	REAL,
	"VisibleSurface_Output"	REAL,
	"VisibleSurface_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"ProfileHeight"	REAL,
	"ProfileHeight_Output"	REAL,
	"ProfileHeight_Unit"	TEXT,
	"ProfileWidth"	REAL,
	"ProfileWidth_Output"	REAL,
	"ProfileWidth_Unit"	TEXT,
	"ProfileUsage"	INTEGER,
	"ProfileClass"	INTEGER,
	"AreaOffer"	TEXT,
	"UsageOffer"	TEXT,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"Picture6_File"	TEXT,
	"Picture6_WidthMM"	REAL,
	"Picture6_HeightMM"	REAL,
	"Picture6_Scale"	REAL,
	"Picture6_Inside"	INTEGER,
	"Picture6_CompCad"	BLOB,
	"Picture7_File"	TEXT,
	"Picture7_WidthMM"	REAL,
	"Picture7_HeightMM"	REAL,
	"Picture7_Scale"	REAL,
	"Picture7_Inside"	INTEGER,
	"Picture7_CompCad"	BLOB,
	"PictureCuttingDetail18_File"	TEXT,
	"PictureCuttingDetail18_WidthMM"	REAL,
	"PictureCuttingDetail18_HeightMM"	REAL,
	"PictureCuttingDetail18_Scale"	REAL,
	"PictureCuttingDetail18_Inside"	INTEGER,
	"PictureCuttingDetail18_CompCad"	BLOB,
	"PictureCuttingDetail19_File"	TEXT,
	"PictureCuttingDetail19_WidthMM"	REAL,
	"PictureCuttingDetail19_HeightMM"	REAL,
	"PictureCuttingDetail19_Scale"	REAL,
	"PictureCuttingDetail19_Inside"	INTEGER,
	"PictureCuttingDetail19_CompCad"	BLOB,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	"DoNotEstimate"	INTEGER DEFAULT 0,
	"BottomExtension"	REAL,
	"BottomExtension_Output"	REAL,
	"BottomExtension_Unit"	TEXT,
	"TopExtension"	REAL,
	"TopExtension_Output"	REAL,
	"TopExtension_Unit"	TEXT,
	"ExtensionSideA"	REAL,
	"ExtensionSideA_Output"	REAL,
	"ExtensionSideA_Unit"	TEXT,
	"ExtensionSideB"	REAL,
	"ExtensionSideB_Output"	REAL,
	"ExtensionSideB_Unit"	TEXT,
	"InsideOutside"	INTEGER,
	"SubNo"	INTEGER,
	"Dimension1"	REAL,
	"Dimension1_Output"	REAL,
	"Dimension1_Unit"	TEXT,
	"Dimension2"	REAL,
	"Dimension2_Output"	REAL,
	"Dimension2_Unit"	TEXT,
	"AngleOfArc"	REAL,
	"PictureBending_File"	TEXT,
	"PictureBending_WidthMM"	REAL,
	"PictureBending_HeightMM"	REAL,
	"PictureBending_Scale"	REAL,
	"PictureBending_Inside"	INTEGER,
	"PictureBending_CompCad"	BLOB,
	"WoodType"	INTEGER,
	"WoodTypeDescription"	TEXT,
	"ArticleTypePrintout"	INTEGER,
	"AlwaysCalculateWholeBar"	INTEGER DEFAULT 0,
	"Validity"	INTEGER,
	"CroppedType"	INTEGER,
	"Cropped"	REAL,
	"Cropped_Output"	REAL,
	"Cropped_Unit"	TEXT,
	"WeightEstimation"	REAL,
	"WeightEstimation_Output"	REAL,
	"WeightEstimation_Unit"	TEXT,
	"HandleHeight"	REAL,
	"HandleHeight_Output"	REAL,
	"HandleHeight_Unit"	TEXT,
	"RebateDimension"	REAL,
	"RebateDimension_Output"	REAL,
	"RebateDimension_Unit"	TEXT,
	"ProfileGroup"	TEXT,
	"ProfileSubType"	INTEGER,
	PRIMARY KEY("ProfileID"),
	FOREIGN KEY("InsertionId") REFERENCES "Insertions"("InsertionID")
);
CREATE TABLE IF NOT EXISTS "ProjectVariables" (
	"ProjectVariableId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"SelectedValue"	TEXT,
	"ProjectId"	INTEGER NOT NULL,
	PRIMARY KEY("ProjectVariableId"),
	FOREIGN KEY("ProjectId") REFERENCES "Projects"("ProjectID")
);
CREATE TABLE IF NOT EXISTS "Projects" (
	"ProjectID"	INTEGER NOT NULL,
	"LK_CustomerAddressID"	INTEGER,
	"LK_ShippingAddressID"	INTEGER,
	"Name"	TEXT,
	"xGUID"	TEXT,
	"OrderNo"	TEXT,
	"OfferNo"	TEXT,
	"DeliveryNo"	TEXT,
	"InvoiceNo"	TEXT,
	"ActiveTitle"	TEXT,
	"ProjectPath"	TEXT,
	"EstimationDataName"	TEXT,
	"OfferDiscount1"	REAL,
	"OfferDiscount2"	REAL,
	"OfferDiscount3"	REAL,
	"OfferDiscount4"	REAL,
	"MaxOfferDiscount1"	REAL,
	"MaxOfferDiscount2"	REAL,
	"MaxOfferDiscount3"	REAL,
	"MaxOfferDiscount4"	REAL,
	"PersonInCharge"	TEXT,
	"PersonInChargeTech"	TEXT,
	"PictureFile"	TEXT,
	"TextBegin"	TEXT,
	"TextEnd"	TEXT,
	"ProjectType"	INTEGER,
	"Comment_1"	TEXT,
	"Comment_2"	TEXT,
	"Comment_3"	TEXT,
	"Comment_4"	TEXT,
	"Comment_5"	TEXT,
	"Fabrication1"	REAL,
	"Fabrication2"	REAL,
	"Fabrication3"	REAL,
	"Fabrication4"	REAL,
	"Fabrication5"	REAL,
	"Fabrication6"	REAL,
	"Fabrication7"	REAL,
	"Fabrication8"	REAL,
	"Fabrication9"	REAL,
	"Fabrication10"	REAL,
	"Fabrication11"	REAL,
	"Fabrication12"	REAL,
	"Fabrication13"	REAL,
	"Fabrication14"	REAL,
	"Fabrication15"	REAL,
	"Installation1"	REAL,
	"Installation2"	REAL,
	"Dismantling"	REAL,
	"WorkPreparation1"	REAL,
	"WorkPreparation2"	REAL,
	"WorkPreparation3"	REAL,
	"SealingCosts"	REAL,
	"SiliconeGlazingCosts"	REAL,
	"WindowGlazingCosts"	REAL,
	"WindowPanelingCosts"	REAL,
	"WindowMinGlazingCosts"	REAL,
	"WindowMinPanelingCosts"	REAL,
	"CurtainWallGlazingCosts"	REAL,
	"CurtainWallPanelingCosts"	REAL,
	"CurtainWallMinGlazingCosts"	REAL,
	"CurtainWallMinPanelingCosts"	REAL,
	"PackagingSurcharge"	REAL,
	"DualColorSurcharge"	REAL,
	"PrcOverheadsMaterial"	REAL,
	"PrcOverheadsGlass"	REAL,
	"PrcOverheadsWages"	REAL,
	"PrcOverheadsPanel"	REAL,
	"PrcSealingToStructure"	REAL,
	"PrcRollProfiles"	REAL,
	"PrcTaping"	REAL,
	"PrcExtra"	REAL,
	"PrcSalesManagement"	REAL,
	"PrcInterest"	REAL,
	"PrcTransport"	REAL,
	"PrcProfitWages"	REAL,
	"PrcProfitMaterial"	REAL,
	"PrcProfitWastage"	REAL,
	"PrcProfitGlass"	REAL,
	"PrcProfitPanel"	REAL,
	"PrcProfitElement"	REAL,
	"PrcProfitOther"	REAL,
	"PrcTotalPriceProfit"	REAL,
	"PrcPlanningOffice"	REAL,
	"PrcCommission"	REAL,
	"PrcSurchargeCashDiscount"	REAL,
	"CreationDate"	TEXT,
	"FreeText1"	TEXT,
	"FreeText2"	TEXT,
	"FreeText3"	TEXT,
	"ACTIVEID"	INTEGER,
	PRIMARY KEY("ProjectID")
);
CREATE TABLE IF NOT EXISTS "REPORTVARIABLES" (
	"ID"	INTEGER NOT NULL,
	"SubNode"	STRING,
	"FieldName"	STRING,
	"SValue"	TEXT,
	"FieldType"	INTEGER,
	"FieldDescription"	STRING,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "ReportOfferTexts" (
	"ReportOfferTextID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Link"	TEXT,
	"Description"	TEXT,
	"Optional"	INTEGER DEFAULT 0,
	"Main"	INTEGER DEFAULT 0,
	"SalesPriceItem"	INTEGER DEFAULT 0,
	"Price"	REAL,
	"GrossPrice"	REAL,
	"TotalPrice"	REAL,
	"DealerTotalPrice"	REAL,
	"GrossTotalPrice"	REAL,
	"PriceWages"	REAL,
	"GrossPriceWages"	REAL,
	PRIMARY KEY("ReportOfferTextID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "SashGlazingBeadInfos" (
	"GlazingBeadInfoId"	INTEGER NOT NULL,
	"SashId"	INTEGER NOT NULL,
	"MeasureId"	INTEGER,
	"GlazingBeadGuid"	TEXT,
	"GlazingBeadLength"	REAL,
	"GlazingBeadLength_Output"	REAL,
	"GlazingBeadLength_Unit"	TEXT,
	"DimLength"	REAL,
	"DimLength_Output"	REAL,
	"DimLength_Unit"	TEXT,
	"Name"	TEXT,
	PRIMARY KEY("GlazingBeadInfoId"),
	FOREIGN KEY("SashId") REFERENCES "Sashes"("SashId")
);
CREATE TABLE IF NOT EXISTS "SashPartInfos" (
	"SashPartInfoId"	INTEGER NOT NULL,
	"SashPartId"	INTEGER NOT NULL,
	"InfoName"	TEXT,
	"ValueText"	TEXT,
	"ValueDim"	REAL,
	"ValueDim_Output"	REAL,
	"ValueDim_Unit"	TEXT,
	"ValueInt"	INTEGER,
	PRIMARY KEY("SashPartInfoId"),
	FOREIGN KEY("SashPartId") REFERENCES "SashParts"("SashPartId")
);
CREATE TABLE IF NOT EXISTS "SashParts" (
	"SashPartId"	INTEGER NOT NULL,
	"SashId"	INTEGER NOT NULL,
	"CncTypeNo"	INTEGER,
	"CncType"	TEXT,
	"CncName"	TEXT,
	"PosX"	REAL,
	"PosX_Output"	REAL,
	"PosX_Unit"	TEXT,
	"PosY"	REAL,
	"PosY_Output"	REAL,
	"PosY_Unit"	TEXT,
	"Side"	INTEGER,
	PRIMARY KEY("SashPartId"),
	FOREIGN KEY("SashId") REFERENCES "Sashes"("SashId")
);
CREATE TABLE IF NOT EXISTS "Sashes" (
	"SashId"	INTEGER NOT NULL,
	"InsertionId"	INTEGER NOT NULL,
	"xGUID"	TEXT,
	"DIN"	TEXT,
	"SliderDirection"	TEXT,
	"Nr"	INTEGER,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"MasterLeaf"	INTEGER DEFAULT 0,
	"SlaveLeaf"	INTEGER DEFAULT 0,
	"PictureI_File"	TEXT,
	"PictureI_WidthMM"	REAL,
	"PictureI_HeightMM"	REAL,
	"PictureI_Scale"	REAL,
	"PictureI_Inside"	INTEGER,
	"PictureI_CompCad"	BLOB,
	"PictureO_File"	TEXT,
	"PictureO_WidthMM"	REAL,
	"PictureO_HeightMM"	REAL,
	"PictureO_Scale"	REAL,
	"PictureO_Inside"	INTEGER,
	"PictureO_CompCad"	BLOB,
	"GasketPicture_File"	TEXT,
	"GasketPicture_WidthMM"	REAL,
	"GasketPicture_HeightMM"	REAL,
	"GasketPicture_Scale"	REAL,
	"GasketPicture_Inside"	INTEGER,
	"GasketPicture_CompCad"	BLOB,
	"HardwarePicture_File"	TEXT,
	"HardwarePicture_WidthMM"	REAL,
	"HardwarePicture_HeightMM"	REAL,
	"HardwarePicture_Scale"	REAL,
	"HardwarePicture_Inside"	INTEGER,
	"HardwarePicture_CompCad"	BLOB,
	"GLLMeasurePicture_File"	TEXT,
	"GLLMeasurePicture_WidthMM"	REAL,
	"GLLMeasurePicture_HeightMM"	REAL,
	"GLLMeasurePicture_Scale"	REAL,
	"GLLMeasurePicture_Inside"	INTEGER,
	"GLLMeasurePicture_CompCad"	BLOB,
	"ClearanceTop"	REAL,
	"ClearanceTop_Output"	REAL,
	"ClearanceTop_Unit"	TEXT,
	"ClearanceLock"	REAL,
	"ClearanceLock_Output"	REAL,
	"ClearanceLock_Unit"	TEXT,
	"ClearanceHinge"	REAL,
	"ClearanceHinge_Output"	REAL,
	"ClearanceHinge_Unit"	TEXT,
	"MountingWithGlazingBars"	INTEGER DEFAULT 0,
	PRIMARY KEY("SashId"),
	FOREIGN KEY("InsertionId") REFERENCES "Insertions"("InsertionID")
);
CREATE TABLE IF NOT EXISTS "Saws" (
	"SawID"	INTEGER NOT NULL,
	"SawName"	TEXT,
	"DimensionDefinition"	INTEGER,
	"IsDummySaw"	INTEGER DEFAULT 0,
	"Priority"	INTEGER,
	"Type"	INTEGER,
	"LengthDimsRefersTo"	INTEGER,
	"UsedTools"	TEXT,
	"CNCExportFile"	TEXT,
	"ActiveTitle"	TEXT,
	"BarCodeType"	INTEGER,
	PRIMARY KEY("SawID")
);
CREATE TABLE IF NOT EXISTS "Segments" (
	"SegmentId"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"xGUID"	TEXT,
	"ProfileType"	INTEGER,
	"InsideX0"	REAL,
	"InsideY0"	REAL,
	"InsideX1"	REAL,
	"InsideY1"	REAL,
	"OutsideX0"	REAL,
	"OutsideY0"	REAL,
	"OutsideX1"	REAL,
	"OutsideY1"	REAL,
	"PictureI_File"	TEXT,
	"PictureI_WidthMM"	REAL,
	"PictureI_HeightMM"	REAL,
	"PictureI_Scale"	REAL,
	"PictureI_Inside"	INTEGER,
	"PictureI_CompCad"	BLOB,
	"PictureO_File"	TEXT,
	"PictureO_WidthMM"	REAL,
	"PictureO_HeightMM"	REAL,
	"PictureO_Scale"	REAL,
	"PictureO_Inside"	INTEGER,
	"PictureO_CompCad"	BLOB,
	"PictureTotalI_File"	TEXT,
	"PictureTotalI_WidthMM"	REAL,
	"PictureTotalI_HeightMM"	REAL,
	"PictureTotalI_Scale"	REAL,
	"PictureTotalI_Inside"	INTEGER,
	"PictureTotalI_CompCad"	BLOB,
	"PictureTotalO_File"	TEXT,
	"PictureTotalO_WidthMM"	REAL,
	"PictureTotalO_HeightMM"	REAL,
	"PictureTotalO_Scale"	REAL,
	"PictureTotalO_Inside"	INTEGER,
	"PictureTotalO_CompCad"	BLOB,
	"PictureWithWholeElevationI_File"	TEXT,
	"PictureWithWholeElevationI_WidthMM"	REAL,
	"PictureWithWholeElevationI_HeightMM"	REAL,
	"PictureWithWholeElevationI_Scale"	REAL,
	"PictureWithWholeElevationI_Inside"	INTEGER,
	"PictureWithWholeElevationI_CompCad"	BLOB,
	"PictureWithWholeElevationO_File"	TEXT,
	"PictureWithWholeElevationO_WidthMM"	REAL,
	"PictureWithWholeElevationO_HeightMM"	REAL,
	"PictureWithWholeElevationO_Scale"	REAL,
	"PictureWithWholeElevationO_Inside"	INTEGER,
	"PictureWithWholeElevationO_CompCad"	BLOB,
	"ElevationGUID"	TEXT,
	"LastGUID"	TEXT,
	PRIMARY KEY("SegmentId"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "SingleElevations" (
	"SingleElevationID"	INTEGER NOT NULL,
	"ElevationGroupId"	INTEGER NOT NULL,
	"LK_BaseInnerColorId"	INTEGER,
	"LK_BaseOuterColorId"	INTEGER,
	"LK_InsertionInnerColorId"	INTEGER,
	"LK_InsertionOuterColorId"	INTEGER,
	"Name"	TEXT,
	"xGUID"	TEXT,
	"LinkedGUID"	TEXT,
	"LinkComment"	TEXT,
	"Amount"	REAL,
	"OrgAmount"	REAL,
	"InsertionGuidlinesLikeProject"	INTEGER DEFAULT 0,
	"OnlyEstimation"	INTEGER DEFAULT 0,
	"Alternative"	INTEGER DEFAULT 0,
	"Description"	TEXT,
	"TextPosText"	TEXT,
	"AutoDescription"	TEXT,
	"AutoDescriptionShort"	TEXT,
	"Model"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"Area"	REAL,
	"Area_Output"	REAL,
	"Area_Unit"	TEXT,
	"SystemCode"	TEXT,
	"SystemCode_Supplier"	TEXT,
	"SystemCode_Number"	TEXT,
	"SystemCode_BaseNumber"	TEXT,
	"SystemCode_OrderCode"	TEXT,
	"SystemCode_OriginalNumber"	TEXT,
	"SystemName"	TEXT,
	"SystemLongName"	TEXT,
	"SystemNameInternal"	TEXT,
	"SystemType"	INTEGER,
	"SystemRulePackage"	TEXT,
	"SystemGLL"	TEXT,
	"SystemSub"	TEXT,
	"SystemSelection1"	TEXT,
	"SystemSelection2"	TEXT,
	"SubSystemAsMainSystem"	INTEGER DEFAULT 0,
	"ElevationType"	INTEGER,
	"WoodType"	INTEGER,
	"WoodTypeDescription"	TEXT,
	"WoodDepth"	REAL,
	"WoodDepth_Output"	REAL,
	"WoodDepth_Unit"	TEXT,
	"Drainage"	INTEGER,
	"TConnections"	INTEGER,
	"TConnections_Description"	TEXT,
	"Corners"	INTEGER,
	"Corners_Description"	TEXT,
	"BaseCorners"	INTEGER,
	"BaseCorners_Description"	TEXT,
	"WindowCorners"	INTEGER,
	"WindowCorners_Description"	TEXT,
	"SashCorners"	INTEGER,
	"SashCorners_Description"	TEXT,
	"DoorCorners"	INTEGER,
	"DoorCorners_Description"	TEXT,
	"LengthDimsReferTo"	INTEGER,
	"SegmentLevel"	INTEGER,
	"IsSegment"	INTEGER DEFAULT 0,
	"Material"	TEXT,
	"CWConnectionInside"	TEXT,
	"CWConnectionOutside"	TEXT,
	"ImportOrigin"	INTEGER,
	"TextPosOrigin"	INTEGER,
	"SubNo"	INTEGER,
	"CEDataComplete"	INTEGER DEFAULT 0,
	"StaticCalculation"	INTEGER DEFAULT 0,
	"IsCurrentVersion"	INTEGER DEFAULT 0,
	"OffsetX"	REAL,
	"OffsetX_Output"	REAL,
	"OffsetX_Unit"	TEXT,
	"OffsetY"	REAL,
	"OffsetY_Output"	REAL,
	"OffsetY_Unit"	TEXT,
	"CreatedBy"	TEXT,
	"CreatedOn"	TEXT,
	"ChangedBy"	TEXT,
	"ChangedOn"	TEXT,
	"Picture1_File"	TEXT,
	"Picture1_WidthMM"	REAL,
	"Picture1_HeightMM"	REAL,
	"Picture1_Scale"	REAL,
	"Picture1_Inside"	INTEGER,
	"Picture1_CompCad"	BLOB,
	"Picture2_File"	TEXT,
	"Picture2_WidthMM"	REAL,
	"Picture2_HeightMM"	REAL,
	"Picture2_Scale"	REAL,
	"Picture2_Inside"	INTEGER,
	"Picture2_CompCad"	BLOB,
	"Picture3_File"	TEXT,
	"Picture3_WidthMM"	REAL,
	"Picture3_HeightMM"	REAL,
	"Picture3_Scale"	REAL,
	"Picture3_Inside"	INTEGER,
	"Picture3_CompCad"	BLOB,
	"Picture4_File"	TEXT,
	"Picture4_WidthMM"	REAL,
	"Picture4_HeightMM"	REAL,
	"Picture4_Scale"	REAL,
	"Picture4_Inside"	INTEGER,
	"Picture4_CompCad"	BLOB,
	"Picture5_File"	TEXT,
	"Picture5_WidthMM"	REAL,
	"Picture5_HeightMM"	REAL,
	"Picture5_Scale"	REAL,
	"Picture5_Inside"	INTEGER,
	"Picture5_CompCad"	BLOB,
	"SurveyPicture_File"	TEXT,
	"SurveyPicture_WidthMM"	REAL,
	"SurveyPicture_HeightMM"	REAL,
	"SurveyPicture_Scale"	REAL,
	"SurveyPicture_Inside"	INTEGER,
	"SurveyPicture_CompCad"	BLOB,
	"ProfileMem"	TEXT,
	"ProfileMemBlob"	,
	"ProfileMemBlobIsZipped"	INTEGER DEFAULT 0,
	"SealingToStructure"	INTEGER,
	"GlassGasket"	INTEGER,
	"CentreGasket"	INTEGER,
	"Manufacturing"	REAL,
	"Manufacturing2"	REAL,
	"Manufacturing3"	REAL,
	"Manufacturing4"	REAL,
	"Manufacturing5"	REAL,
	"Manufacturing6"	REAL,
	"Manufacturing7"	REAL,
	"Manufacturing8"	REAL,
	"Manufacturing9"	REAL,
	"Manufacturing10"	REAL,
	"Manufacturing11"	REAL,
	"Manufacturing12"	REAL,
	"Manufacturing13"	REAL,
	"Manufacturing14"	REAL,
	"Manufacturing15"	REAL,
	"Mounting"	REAL,
	"Mounting2"	REAL,
	"Dismantling"	REAL,
	"JobPlanning"	REAL,
	"JobPlanning2"	REAL,
	"JobPlanning3"	REAL,
	"Sealing"	REAL,
	"Taping"	REAL,
	"ColorBase"	TEXT,
	"ColorBase_Long"	TEXT,
	"ColorInsertions"	TEXT,
	"ColorInsertions_Long"	TEXT,
	"CEText"	TEXT,
	"CalculationComment"	TEXT,
	"MountingComment"	TEXT,
	"OfferComment"	TEXT,
	"OrderComment"	TEXT,
	"DeliveryComment"	TEXT,
	"CrossSectionComment"	TEXT,
	"InvoiceComment"	TEXT,
	"MESComment"	TEXT,
	"TextPosPicture"	TEXT,
	"ActiveTitle"	TEXT,
	"Units"	TEXT,
	"TextPosNoQuotation"	INTEGER DEFAULT 0,
	"ColorBaseRGB1"	INTEGER,
	"ColorWindowRGB1"	INTEGER,
	"ColorDoorRGB1"	INTEGER,
	"ColorBaseRGB2"	INTEGER,
	"ColorWindowRGB2"	INTEGER,
	"ColorDoorRGB2"	INTEGER,
	"HasDoors"	INTEGER DEFAULT 0,
	"HasSliders"	INTEGER DEFAULT 0,
	"Status"	INTEGER,
	"JustDoorpackage"	INTEGER DEFAULT 0,
	"SegmentGUID"	TEXT,
	"HasEnergyLabel"	INTEGER DEFAULT 0,
	"EnergyLabelAllowed"	INTEGER DEFAULT 0,
	"HistoryGroupId"	INTEGER,
	"WarningLevel"	INTEGER,
	"EnergyLabelErrCode"	INTEGER,
	"HistoryDate"	TEXT,
	"HistoryComment"	TEXT,
	"SurfaceWastage"	REAL,
	"AccessorieWastage"	REAL,
	"CoatingWastage"	REAL,
	"HardwareWastage"	REAL,
	"ProfileWastage"	REAL,
	"WoddenProfileWastage"	REAL,
	"JustReplacePackage"	INTEGER DEFAULT 0,
	"FixedPriceTotal"	REAL,
	"FixedPriceGlass"	REAL,
	"HistoryPhase"	INTEGER,
	"HasWindows"	INTEGER DEFAULT 0,
	"SubId"	INTEGER,
	"GroupId"	INTEGER,
	"UseLabourTimeSuggestion"	INTEGER DEFAULT 0,
	"SubStructureSegmentType"	INTEGER,
	"InsideOutSideSegmentType"	INTEGER,
	"ColorBaseLongInfo"	TEXT,
	"ColorInsertionsLongInfo"	TEXT,
	"FireProtectionClass"	INTEGER,
	"FireProtectionDuration"	INTEGER,
	"IsArchedOrSlanted"	INTEGER DEFAULT 0,
	"IsFreeCad"	INTEGER DEFAULT 0,
	"HasAlignedProfiles"	INTEGER DEFAULT 0,
	"LK_VATRateId"	INTEGER NOT NULL,
	"ScrewInfluenceAddition"	REAL,
	"ScrewInfluenceAddition_Output"	REAL,
	"ScrewInfluenceAddition_Unit"	TEXT,
	"IsSmokeProtection"	INTEGER DEFAULT 0,
	"IsInsertionElement"	INTEGER DEFAULT 0,
	"DatasafeQrCode"	TEXT,
	"BaseElementGUID"	TEXT,
	"LastGUID"	TEXT,
	"DoorpackageExplodeOption"	INTEGER,
	"HorizontalCrossSectionCutPicture_File"	TEXT,
	"HorizontalCrossSectionCutPicture_WidthMM"	REAL,
	"HorizontalCrossSectionCutPicture_HeightMM"	REAL,
	"HorizontalCrossSectionCutPicture_Scale"	REAL,
	"HorizontalCrossSectionCutPicture_Inside"	INTEGER,
	"HorizontalCrossSectionCutPicture_CompCad"	BLOB,
	"VerticalCrossSectionCutPicture_File"	TEXT,
	"VerticalCrossSectionCutPicture_WidthMM"	REAL,
	"VerticalCrossSectionCutPicture_HeightMM"	REAL,
	"VerticalCrossSectionCutPicture_Scale"	REAL,
	"VerticalCrossSectionCutPicture_Inside"	INTEGER,
	"VerticalCrossSectionCutPicture_CompCad"	BLOB,
	"SteelSerieFrameCoating"	INTEGER DEFAULT 0,
	"FramePicture_File"	TEXT,
	"FramePicture_WidthMM"	REAL,
	"FramePicture_HeightMM"	REAL,
	"FramePicture_Scale"	REAL,
	"FramePicture_Inside"	INTEGER,
	"FramePicture_CompCad"	BLOB,
	"DeclarationType"	INTEGER,
	"ETA_EuropeanAssessmentDocument"	TEXT,
	"ETA_TechnicalAssessment"	TEXT,
	"ETA_TechnicalAssessmentBody"	TEXT,
	"FireProtectionUsage"	INTEGER,
	"LK_ElevationId"	INTEGER NOT NULL,
	"LocationInObject"	TEXT,
	"ElementGUID"	TEXT,
	"InstanceNumber"	INTEGER,
	PRIMARY KEY("SingleElevationID"),
	FOREIGN KEY("ElevationGroupId") REFERENCES "ElevationGroups"("ElevationGroupID"),
	FOREIGN KEY("LK_ElevationId") REFERENCES "Elevations"("ElevationID"),
	FOREIGN KEY("LK_VATRateId") REFERENCES "VATRates"("VATRateId")
);
CREATE TABLE IF NOT EXISTS "SpecialPrices" (
	"SpecialPriceId"	INTEGER NOT NULL,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Color"	TEXT,
	"Price"	REAL,
	"SpecialPriceType"	INTEGER,
	"PriceCurrency"	TEXT,
	"PriceClass"	TEXT,
	"Discount"	REAL,
	"ProjectId"	INTEGER NOT NULL,
	PRIMARY KEY("SpecialPriceId"),
	FOREIGN KEY("ProjectId") REFERENCES "Projects"("ProjectID")
);
CREATE TABLE IF NOT EXISTS "SubAllArticles" (
	"SubAllArticleID"	INTEGER NOT NULL,
	"AllArticleId"	INTEGER NOT NULL,
	"LK_ColorId"	INTEGER,
	"OnlyInfo"	INTEGER DEFAULT 0,
	"ArticleGroup"	TEXT,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"Units"	REAL,
	"Units_Output"	REAL,
	"Units_Unit"	TEXT,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"Info"	TEXT,
	"Color"	TEXT,
	"ColorTypeInternal"	INTEGER,
	"Price"	REAL,
	"PriceGross"	REAL,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"IsLength"	INTEGER DEFAULT 0,
	"IsArea"	INTEGER DEFAULT 0,
	"IsPriceIncluded"	INTEGER DEFAULT 0,
	"ArticleType"	INTEGER,
	"ArticleTypePrintout"	INTEGER,
	"PieceListType"	INTEGER,
	"ProcessingPointType"	INTEGER,
	"LockingBarInfo"	TEXT,
	"LockingBarPosLong"	TEXT,
	"LockingBarPos"	TEXT,
	"SashGUID"	TEXT,
	"IsAdditional"	INTEGER DEFAULT 0,
	PRIMARY KEY("SubAllArticleID"),
	FOREIGN KEY("AllArticleId") REFERENCES "AllArticles"("AllArticleID")
);
CREATE TABLE IF NOT EXISTS "SubArticles" (
	"SubArticleID"	INTEGER NOT NULL,
	"ArticleId"	INTEGER NOT NULL,
	"LK_ColorId"	INTEGER,
	"OnlyInfo"	INTEGER DEFAULT 0,
	"ArticleGroup"	TEXT,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"Units"	REAL,
	"Units_Output"	REAL,
	"Units_Unit"	TEXT,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"Info"	TEXT,
	"Color"	TEXT,
	"ColorTypeInternal"	INTEGER,
	"Price"	REAL,
	"PriceGross"	REAL,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"Width"	REAL,
	"Width_Output"	REAL,
	"Width_Unit"	TEXT,
	"Height"	REAL,
	"Height_Output"	REAL,
	"Height_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"IsLength"	INTEGER DEFAULT 0,
	"IsArea"	INTEGER DEFAULT 0,
	"IsPriceIncluded"	INTEGER DEFAULT 0,
	"ArticleType"	INTEGER,
	"ArticleTypePrintout"	INTEGER,
	"PieceListType"	INTEGER,
	"ProcessingPointType"	INTEGER,
	"LockingBarInfo"	TEXT,
	"LockingBarPosLong"	TEXT,
	"LockingBarPos"	TEXT,
	"SashGUID"	TEXT,
	"IsAdditional"	INTEGER DEFAULT 0,
	PRIMARY KEY("SubArticleID"),
	FOREIGN KEY("ArticleId") REFERENCES "Articles"("ArticleID")
);
CREATE TABLE IF NOT EXISTS "SubProfiles" (
	"SubProfileID"	INTEGER NOT NULL,
	"ProfileBarID"	INTEGER NOT NULL,
	"LK_KfmKeyId"	INTEGER,
	"LK_DiscountId"	INTEGER,
	"LK_ColorId"	INTEGER,
	"ArticleCode"	TEXT,
	"ArticleCode_Supplier"	TEXT,
	"ArticleCode_Number"	TEXT,
	"ArticleCode_BaseNumber"	TEXT,
	"ArticleCode_OrderCode"	TEXT,
	"ArticleCode_OriginalNumber"	TEXT,
	"Amount"	INTEGER,
	"Side"	INTEGER,
	"Description"	TEXT,
	"CustomDescription"	TEXT,
	"Color"	TEXT,
	"InnerColor"	TEXT,
	"OuterColor"	TEXT,
	"IsDualColor"	INTEGER DEFAULT 0,
	"ColorTypeInternal"	INTEGER,
	"ColorInfoInternal"	TEXT,
	"InnerColorTypeInternal"	INTEGER,
	"InnerColorInfoInternal"	TEXT,
	"OuterColorTypeInternal"	INTEGER,
	"OuterColorInfoInternal"	TEXT,
	"ColorCombinationGUID"	TEXT,
	"Price"	REAL,
	"PriceGross"	REAL,
	"PriceCoating"	REAL,
	"Length"	REAL,
	"Length_Output"	REAL,
	"Length_Unit"	TEXT,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"PerimeterBoundaryBox"	REAL,
	"PerimeterBoundaryBox_Output"	REAL,
	"PerimeterBoundaryBox_Unit"	TEXT,
	"VisibleSurface"	REAL,
	"VisibleSurface_Output"	REAL,
	"VisibleSurface_Unit"	TEXT,
	"Weight"	REAL,
	"Weight_Output"	REAL,
	"Weight_Unit"	TEXT,
	"PUSize"	REAL,
	"PUSize_Output"	REAL,
	"PUSize_Unit"	TEXT,
	"SubSize"	REAL,
	"ArticleType"	INTEGER,
	"DeliveryStatus"	INTEGER,
	"SupplierCode"	INTEGER,
	"ProductGroup"	TEXT,
	"Picture12_File"	TEXT,
	"Picture12_WidthMM"	REAL,
	"Picture12_HeightMM"	REAL,
	"Picture12_Scale"	REAL,
	"Picture12_Inside"	INTEGER,
	"Picture12_CompCad"	BLOB,
	"Picture13_File"	TEXT,
	"Picture13_WidthMM"	REAL,
	"Picture13_HeightMM"	REAL,
	"Picture13_Scale"	REAL,
	"Picture13_Inside"	INTEGER,
	"Picture13_CompCad"	BLOB,
	"Picture14_File"	TEXT,
	"Picture14_WidthMM"	REAL,
	"Picture14_HeightMM"	REAL,
	"Picture14_Scale"	REAL,
	"Picture14_Inside"	INTEGER,
	"Picture14_CompCad"	BLOB,
	"CustomerStockItem"	INTEGER DEFAULT 0,
	PRIMARY KEY("SubProfileID"),
	FOREIGN KEY("ProfileBarID") REFERENCES "ProfileBars"("ProfileBarID")
);
CREATE TABLE IF NOT EXISTS "SunShadingInsertions" (
	"Id"	INTEGER NOT NULL,
	"SunShadingId"	INTEGER NOT NULL,
	"InsertionGUID"	TEXT,
	PRIMARY KEY("Id"),
	FOREIGN KEY("SunShadingId") REFERENCES "SunShadings"("Id")
);
CREATE TABLE IF NOT EXISTS "SunShadings" (
	"Id"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"ArticleId"	INTEGER NOT NULL,
	"ConfigurationId"	TEXT,
	"Supplierdata"	TEXT,
	"SunShadingSupplier"	INTEGER,
	"Width"	REAL,
	"Height"	REAL,
	"OrderId"	TEXT,
	"TransActionType"	INTEGER,
	PRIMARY KEY("Id"),
	FOREIGN KEY("ArticleId") REFERENCES "AllArticles"("AllArticleID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "Suppliers" (
	"SupplierID"	INTEGER NOT NULL,
	"LK_DeliveryAddressID"	INTEGER,
	"LK_VendorAddressID"	INTEGER,
	"Address1"	TEXT,
	"Address2"	TEXT,
	"Address3"	TEXT,
	"Address4"	TEXT,
	"Address5"	TEXT,
	"Address6"	TEXT,
	"Address7"	TEXT,
	"Address8"	TEXT,
	"Address9"	TEXT,
	"CustomerNo"	TEXT,
	"Phone1"	TEXT,
	"Phone2"	TEXT,
	"Fax"	TEXT,
	"Email"	TEXT,
	"ColSortOutsideInside"	INTEGER DEFAULT 0,
	"PriceLevel"	TEXT,
	"ActiveTitle"	TEXT,
	"ZipCode"	TEXT,
	PRIMARY KEY("SupplierID")
);
CREATE TABLE IF NOT EXISTS "Tools" (
	"ToolID"	INTEGER NOT NULL,
	"SawId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"ToolLength"	REAL,
	"ToolLength_Output"	REAL,
	"ToolLength_Unit"	TEXT,
	"HolderLength"	REAL,
	"HolderLength_Output"	REAL,
	"HolderLength_Unit"	TEXT,
	PRIMARY KEY("ToolID"),
	FOREIGN KEY("SawId") REFERENCES "Saws"("SawID")
);
CREATE TABLE IF NOT EXISTS "UValue" (
	"UValueID"	INTEGER NOT NULL,
	"ElevationId"	INTEGER NOT NULL,
	"LK_GlassId"	INTEGER,
	"LK_UValueInstituteId"	INTEGER,
	"Name"	TEXT,
	"IsSummary"	INTEGER DEFAULT 0,
	"ValueType"	INTEGER,
	"SourceType"	INTEGER,
	"U"	REAL,
	"U_Output"	REAL,
	"U_Unit"	TEXT,
	"UDigits"	INTEGER,
	"Psi"	REAL,
	"Psi_Output"	REAL,
	"Psi_Unit"	TEXT,
	"PsiDigits"	INTEGER,
	"PsiInsertions"	REAL,
	"Area"	REAL,
	"Area_Output"	REAL,
	"Area_Unit"	TEXT,
	"AreaMissing"	REAL,
	"AreaMissing_Output"	REAL,
	"AreaMissing_Unit"	TEXT,
	"UBaseProfiles"	REAL,
	"Perimeter"	REAL,
	"Perimeter_Output"	REAL,
	"Perimeter_Unit"	TEXT,
	"PerimeterInsertions"	REAL,
	"IsDefault"	INTEGER DEFAULT 0,
	"Report"	TEXT,
	"Institute"	INTEGER,
	"UValueAdjustmentReason"	INTEGER,
	"UValueOrigin"	INTEGER,
	PRIMARY KEY("UValueID"),
	FOREIGN KEY("ElevationId") REFERENCES "Elevations"("ElevationID")
);
CREATE TABLE IF NOT EXISTS "UValueInstitutes" (
	"UValueInstituteId"	INTEGER NOT NULL,
	"InstituteName"	TEXT,
	PRIMARY KEY("UValueInstituteId")
);
CREATE TABLE IF NOT EXISTS "VATRates" (
	"VATRateId"	INTEGER NOT NULL,
	"Name"	TEXT,
	"xGUID"	TEXT,
	"Rate"	REAL,
	PRIMARY KEY("VATRateId")
);
COMMIT;
